### ISSUE TITLE
Error: cannot drop air

### ISSUE THREAD

**Issue by FrankHeijden** [filoghost/HolographicDisplays#111]
```
16.11 17:25:18 [Server] ERROR Could not pass event ChunkLoadEvent to HolographicDisplays v2.3.2-SNAPSHOT
16.11 17:25:18 [Server] INFO org.bukkit.event.EventException: null
16.11 17:25:18 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.Chunk.addEntities(Chunk.java:977) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:533) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:116) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:110) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:105) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1067) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at java.lang.Thread.run(Thread.java:844) [?:?]
16.11 17:25:18 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot drop air
16.11 17:25:18 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at net.minecraft.server.v1_13_R2.EntityItem.setItemStack(EntityItem.java:409) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.EntityNMSItem.setItemStackNMS(EntityNMSItem.java:201) ~[?:?]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.spawnNMSItem(NmsManagerImpl.java:90) ~[?:?]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.spawn(CraftItemLine.java:87) ~[?:?]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) ~[?:?]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.object.PluginHologramManager.onChunkLoad(PluginHologramManager.java:66) ~[?:?]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.listener.MainListener.processChunkLoad(MainListener.java:102) ~[?:?]
16.11 17:25:18 [Server] INFO at com.gmail.filoghost.holographicdisplays.listener.MainListener.onChunkLoad(MainListener.java:87) ~[?:?]
16.11 17:25:18 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source) ~[?:?]
16.11 17:25:18 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-447]
16.11 17:25:18 [Server] INFO ... 13 more
```

**Comment by filoghost** [comment]
Now air can be used, since v3 directly uses packets.
