### ISSUE TITLE
1.13.2 Spigot Error

### ISSUE THREAD

**Issue by MWLVegas** [filoghost/HolographicDisplays#116]
Updated to the most recent build of 1.13.2 last night (140f654-c64fe50) and HD will no longer load:

[Server thread/WARN]: [HolographicDisplays] Task #55 for HolographicDisplays v2.3.2-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.WorldServer.getChunkProviderServer()Lnet/minecraft/server/v1_13_R2/ChunkProviderServer;
  at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:125) ~[?:?]
  at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:113) ~[?:?]
  at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) ~[?:?]
  at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) ~[?:?]
  at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) ~[?:?]
  at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) ~[?:?]
  at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-140f654-c64fe50]
  at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-140f654-c64fe50]
  at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-140f654-c64fe50]
  at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-140f654-c64fe50]
  at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-140f654-c64fe50]
  at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-140f654-c64fe50]
  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by filoghost** [comment]
Please try a new development build from https://ci.filoghost.me/job/HolographicDisplays
