### ISSUE TITLE
Unable to compile (Instructions Needed)

### ISSUE THREAD

**Issue by Zilacon** [filoghost/HolographicDisplays#121]
My developers were attempting to fix our problem by removing "Validator.isTrue(Bukkit.isPrimaryThread(), "Async entity add");" as seen on this error here:

```
01-27 14:42:47 [SEVERE] [Minecraft] Could not pass event ChunkLoadEvent to HolographicDisplays v2.1.13
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at net.minecraft.world.gen.ChunkProviderServer.fireBukkitLoadEvent(ThreadedChunkProvider.java)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAtInternal(ThreadedChunkProvider.java:643)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ThreadedChunkProvider.java:519)
    at nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:949)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.IllegalArgumentException: Async entity add
    at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:13)
    at com.gmail.filoghost.holographicdisplays.nms.v1_6_R3.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:111)
    at com.gmail.filoghost.holographicdisplays.nms.v1_6_R3.NmsManagerImpl.spawnNMSHorse(NmsManagerImpl.java:69)
    at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:76)
    at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:300)
    at com.gmail.filoghost.holographicdisplays.object.NamedHologramManager.onChunkLoad(NamedHologramManager.java:49)
    at com.gmail.filoghost.holographicdisplays.listener.MainListener.onChunkLoad(MainListener.java:63)
    at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435)
    ... 11 more
```

The problem is on our 1.6.4 servers we use a software called TickThreading which can be found here: https://github.com/MinimallyCorrect/TickThreading/tree/1.6.4

Which runs as the main server thread, and we believe it is conflicting with holograms because of this. So removing this would possibly fix it. However there is no build instructions for the source for maven or gradle and they are having problems getting it to compile.

Is there any way you could provide instructions as to how to compile it?
Thanks.

**Comment by sgdc3** [comment]
it should compile with a simple "mvn clean package" command :/ no additional steps are required

**Comment by theresajayne** [comment]
The version we need to compile doesnt have Maven or Gradle build files
We need to work from commit 1a0b4d53 as the next one beyond that is "Drop 1.6.4 support" and we are trying to use this on our 1.6.4 packs.

**Comment by filoghost** [comment]
It looks like it wasn't even committed. You can try one of these options:
- Remove all references to the "holograms.api" package
- Copy the package from the last commit before it was deleted https://github.com/filoghost/HolographicDisplays/tree/58ca0491497a52f299f6fa4f156d07bd697a3ae7

**Comment by Zilacon** [comment]
Alright we got a working version going for 1.6.4, onto our issues with 1.7.10 in another issue.
