### ISSUE TITLE
Unable to get a stack trace element...

### ISSUE THREAD

**Issue by B4TT3RY** [filoghost/HolographicDisplays#123]
```
[21:13:14] [Server thread/WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()
	at java.lang.Class.newNoSuchMethodException(Class.java:561) ~[?:1.8.0_202]
	at java.lang.Class.throwExceptionOrReturnNull(Class.java:1194) ~[?:1.8.0_202]
	at java.lang.Class.getMethodHelper(Class.java:1258) ~[?:1.8.0_202]
	at java.lang.Class.getDeclaredMethod(Class.java:930) ~[?:1.8.0_202]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.EntityNMSArmorStand.getId(EntityNMSArmorStand.java:157) ~[?:?]
	at net.minecraft.server.v1_13_R2.PacketPlayOutEntityTeleport.<init>(SourceFile:22) ~[patched_1.13.2.jar:git-Paper-521]
	at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:222) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:112) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.spawn(CraftItemLine.java:88) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshSingleLines(CraftHologram.java:284) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendItemLine(CraftHologram.java:145) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendItemLine(CraftHologram.java:40) ~[?:?]
	at kr.b4tt3ry.btryholoafk.object.AFK.createHologram(AFK.java:132) ~[?:?]
	at kr.b4tt3ry.btryholoafk.object.AFK.enable(AFK.java:27) ~[?:?]
	at kr.b4tt3ry.btryholoafk.Main.lambda$initScheduler$0(Main.java:73) ~[?:?]
	at kr.b4tt3ry.btryholoafk.Main$$Lambda$2244.0000000058F6F4E0.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-521]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
```

I'm using on OpenJDK8-OpenJ9

The error occurs only once, and the hologram looks good.

**Comment by filoghost** [comment]
See my answer here: https://github.com/filoghost/HolographicDisplays/issues/130#issuecomment-497404389
