### ISSUE TITLE
Loading error: ConcurrentModificationException

### ISSUE THREAD

**Issue by madtomic** [filoghost/HolographicDisplays#126]
```[07:33:31 WARN]: [HolographicDisplays] Task #32 for HolographicDisplays v2.3.1 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_201]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_201]
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersManager$1.run(PlaceholdersManager.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paper-1.12.2.jar:git-Paper-1627071d]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[paper-1.12.2.jar:git-Paper-1627071d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[paper-1.12.2.jar:git-Paper-1627071d]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[paper-1.12.2.jar:git-Paper-1627071d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[paper-1.12.2.jar:git-Paper-1627071d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[paper-1.12.2.jar:git-Paper-1627071d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by filoghost** [comment]
To this day, I couldn't figure out what caused the issue. The plugin was heavily refactored for the beta, I hope it doesn't happen anymore.
