### ISSUE TITLE
org.bukkit.plugin.InvalidPluginException:

### ISSUE THREAD

**Issue by StormyIceLeopard** [filoghost/HolographicDisplays#127]
Got any suggestions on how to fix this error?

[17:51:01] [Server thread/ERROR]: Could not load 'plugins\HoloLeaderBoard 1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/placeholder/PlaceholderReplacer
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/placeholder/PlaceholderReplacer
	at net.blizzardcraft.HoloLeaderBoard.HoloLeaderBoard.<init>(HoloLeaderBoard.java:13) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.gmail.filoghost.holographicdisplays.api.placeholder.PlaceholderReplacer
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at net.blizzardcraft.HoloLeaderBoard.HoloLeaderBoard.<init>(HoloLeaderBoard.java:13) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	... 6 more
[17:51:01] [Server thread/INFO]: [HolographicDisplays] Loading HolographicDisplays v2.3.3-SNAPSHOT

**Comment by StormyIceLeopard** [comment]
Okay new issue:
[21:18:39] [Server thread/ERROR]: Error occurred while enabling HoloLeaderBoard v1.0 (Is it up to date?)
java.lang.NullPointerException: null
	at net.blizzardcraft.HoloLeaderBoard.HoloLeaderBoard.onEnable(HoloLeaderBoard.java:33) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by StormyIceLeopard** [comment]
New issue.
This error:
[21:34:15 ERROR]: Could not load 'plugins\HoloLeaderBoard 1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/placeholder/PlaceholderReplacer
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/placeholder/PlaceholderReplacer
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.gmail.filoghost.holographicdisplays.api.placeholder.PlaceholderReplacer
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-fc7ad59-d7bebef]
        ... 6 more

is caused by this code:
HologramsAPI.registerPlaceholder(instance, "{1player}", 300.0, new PlaceholderReplacer() {
			@Override
			public String update() {
				log("Line 1 of inner method", Level.INFO);
				return clb.getInfo(1, "name");
			}
		});

**Comment by StormyIceLeopard** [comment]
I found my issue.
Sorry if I confused anyone.

This return:
return clb.getInfo(1, "name");

is null.
lol rip me
