### ISSUE TITLE
ProtocolLib integration 1.14

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#134]
Spigot 1.14 (2254)
ProtocolLib 4.5.0-b3 (1.14 dev release)
HolographicDisplays 2.3.3-b61

Many similar console errors on player connect. Without ProtocolLib installed, no errors are produced. No errors on Spigot 1.13.2 final with ProtocolLib 4.4.0-b425 or ProtocolLib 4.5.0-b3.
```
[23:16:46] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:174) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.DenizenNetworkManager_v1_14_R1.sendPacket(DenizenNetworkManager_v1_14_R1.java:294) ~[?:?]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1419) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1392) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_14_R1.sendPacket(AbstractListenerPlayIn_v1_14_R1.java:50) ~[?:?]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.DenizenPacketListener_v1_14_R1.sendPacket(DenizenPacketListener_v1_14_R1.java:47) ~[?:?]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:244) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1080) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:944) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$35(PlayerChunkMap.java:535) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$34(PlayerChunkMap.java:534) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$32(PlayerChunkMap.java:530) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:438) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFuture(ChunkProviderServer.java:86) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:66) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IChunkProvider.getChunkAt(SourceFile:15) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:322) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:773) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.Location.getChunk(Location.java:113) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.ugleh.redstoneproximitysensor.utils.RPS.getNearbyEntities(RPS.java:110) [RedstoneProximitySensor-2.3.9.jar:?]
        at com.ugleh.redstoneproximitysensor.utils.RPS.run(RPS.java:131) [RedstoneProximitySensor-2.3.9.jar:?]
        at com.ugleh.redstoneproximitysensor.utils.RPSRunnable.run(RPSRunnable.java:29) [RedstoneProximitySensor-2.3.9.jar:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1009) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:957) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 75.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 70 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}], 
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 70 more
[23:16:46] [Server thread/ERROR]: [HolographicExtension] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicExtension
java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.replacePlaceholders(PacketPlaceholderListener.java:76) ~[?:?]
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacketSending(PacketPlaceholderListener.java:46) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.DenizenNetworkManager_v1_14_R1.sendPacket(DenizenNetworkManager_v1_14_R1.java:294) ~[?:?]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1419) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1392) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_14_R1.sendPacket(AbstractListenerPlayIn_v1_14_R1.java:50) ~[?:?]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.DenizenPacketListener_v1_14_R1.sendPacket(DenizenPacketListener_v1_14_R1.java:47) ~[?:?]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:244) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1080) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:944) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$35(PlayerChunkMap.java:535) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$34(PlayerChunkMap.java:534) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$32(PlayerChunkMap.java:530) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57) ~[spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:438) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFuture(ChunkProviderServer.java:86) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:66) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.IChunkProvider.getChunkAt(SourceFile:15) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:322) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:773) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.Location.getChunk(Location.java:113) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at com.ugleh.redstoneproximitysensor.utils.RPS.getNearbyEntities(RPS.java:110) [RedstoneProximitySensor-2.3.9.jar:?]
        at com.ugleh.redstoneproximitysensor.utils.RPS.run(RPS.java:131) [RedstoneProximitySensor-2.3.9.jar:?]
        at com.ugleh.redstoneproximitysensor.utils.RPSRunnable.run(RPSRunnable.java:29) [RedstoneProximitySensor-2.3.9.jar:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1009) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:957) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar-2019-05-03-0724:git-Spigot-1eece4f-09a453a]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[23:16:46] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutEntityMetadata@3c1be336[
    a=75
    b=[net.minecraft.server.v1_14_R1.DataWatcher$Item@73d73d66, net.minecraft.server.v1_14_R1.DataWatcher$Item@32e570e3, net.minecraft.server.v1_14_R1.DataWatcher$Item@43d075f4, net.minecraft.server.v1_14_R1.DataWatcher$Item@269b0f89, net.minecraft.server.v1_14_R1.DataWatcher$Item@6ced2a31, net.minecraft.server.v1_14_R1.DataWatcher$Item@75163d27, net.minecraft.server.v1_14_R1.DataWatcher$Item@352999a4, net.minecraft.server.v1_14_R1.DataWatcher$Item@4bb03fcf, net.minecraft.server.v1_14_R1.DataWatcher$Item@4e89282a]
  ]
```

**Comment by Totten98** [comment]
Hi,
I also get this error and is very annoying.
I also found out than the {player} and {displayname} variables don't work anymore.

Totten98.

**Comment by SlimeDog** [comment]
[ProtocolLib#600](https://github.com/dmulloy2/ProtocolLib/issues/600) appears to be fixed.

**Comment by Totten98** [comment]
Yeah I can confirm this issue is fixed.

Thanks, Totten98.
