### ISSUE TITLE
Multiple errors and crash on start-up

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#145]
Spigot 1.14.2 (Jenkins 2339) git-Spigot-baafee9-043d31d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Citizens 2.0.25-b1702
Denizen 1.0.6-b838
HolographicDisplays 2.3.3-b73

Spigot and Citizens and Denizen where upgraded over the last few days. There were apparently Spigot NMS changes that HolographicDisplays needs to incorporate.

On start-up, there were multiple ERROR reports, for example:
```
[18:42:22] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Denizen v1.0.6-SNAPSHOT (build 838-DEV)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:551) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$5(PlayerChunk.java:273) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$4(PlayerChunk.java:267) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
        at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:266) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
        at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:204) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:274) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5d8258b7; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
        at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.CraftChunk.getEntities(CraftChunk.java:115) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        at net.aufdemrand.denizen.scripts.containers.core.EntityScriptHelper.onChunkUnload(EntityScriptHelper.java:90) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar-2019-06-02-1422:git-Spigot-baafee9-043d31d]
        ... 22 more
```
leading to server crash. More data available on request.

**Comment by 0xC1A551C** [comment]
same

**Comment by OverBrave** [comment]
same

**Comment by SlimeDog** [comment]
Same behavior with HolographicDisplays 2.3.3-b75.

**Comment by lukemango** [comment]
Getting same issue with MythicMobs & CrateReloaded

**Comment by filoghost** [comment]
See https://github.com/filoghost/HolographicDisplays/issues/148
