### ISSUE TITLE
Not work with latest 1.14.2 server file builds

### ISSUE THREAD

**Issue by andris155** [filoghost/HolographicDisplays#148]
```
[17:12:13] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[17:12:13] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
[17:12:13] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:12:13] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:43)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:126)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:106)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261)
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38)
[17:12:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[17:12:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[17:12:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114)
[17:12:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
[17:12:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
[17:12:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
[17:12:13] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[17:12:13] [Server thread/WARN]: Caused by: java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4affd808; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
[17:12:13] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206)
[17:12:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1149)
[17:12:13] [Server thread/WARN]: 	... 17 more
```
```
[17:12:17] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to HolographicDisplays v2.3.3-SNAPSHOT
java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4affd808; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftChunk.getEntities(CraftChunk.java:115) ~[patched_1.14.2.jar:git-Paper-65]
	at com.gmail.filoghost.holographicdisplays.listener.MainListener.onChunkUnload(MainListener.java:67) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor230.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-65]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:659) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:273) ~[patched_1.14.2.jar:git-Paper-65]
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:267) ~[patched_1.14.2.jar:git-Paper-65]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:266) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.lambda$a$1(ChunkMapDistance.java:126) ~[patched_1.14.2.jar:git-Paper-65]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:124) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:207) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:279) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by AndyK77** [comment]
Having the same issue on latest spigot/paper builds with the latest dev build of HD.

**Comment by cdmvirt** [comment]
same issue here
[crash-2019-06-03_14.16.28-server.txt](https://github.com/filoghost/HolographicDisplays/files/3249530/crash-2019-06-03_14.16.28-server.txt)

**Comment by filoghost** [comment]
Issue is fixed, thanks for the reports everyone. However, please next time check if the problem has already been reported before creating a new bug report.
