### ISSUE TITLE
Dev build console error

### ISSUE THREAD

**Issue by successed** [filoghost/HolographicDisplays#159]
```
[09:03:58 ERROR]: Error occurred while disabling HolographicDisplays v2.3.3-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine cannot be cast to com.gmail.filoghost.holographicdisplays.object.line.CraftHologramLine
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.despawnEntities(CraftHologram.java:310) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onDisable(HolographicDisplays.java:185) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.2.jar:git-Paper-72]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.2.jar:git-Paper-72]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:452) ~[patched_1.14.2.jar:git-Paper-72]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444) ~[patched_1.14.2.jar:git-Paper-72]
        at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:419) ~[?:?]
        at com.rylinaux.plugman.command.UnloadCommand.execute(UnloadCommand.java:112) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.2.jar:git-Paper-72]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-72]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-72]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:698) ~[patched_1.14.2.jar:git-Paper-72]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:457) ~[patched_1.14.2.jar:git-Paper-72]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.14.2.jar:git-Paper-72]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-72]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-72]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by filoghost** [comment]
Something weird happening because CraftTextLine actually extends CraftHologramLine. Don't use plugin reloaders, use `/hd reload`.
