### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by DjeyMute** [filoghost/HolographicDisplays#160]
[18:04:00] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:70) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:79) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:134) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:276) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1229) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:1089) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:770) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:851) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:977) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:451) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1142) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.addPlayer0(WorldServer.java:931) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.addPlayerJoin(WorldServer.java:907) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:229) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 1808.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_162]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_162]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:1.8.0_162]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_162]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_162]
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
[18:04:00] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutSpawnEntityLiving@3f45f158[
    a=1808
    b=210369c6-afdb-4462-ac8e-b73dcab79db5
    c=1
    d=-2479.5
    e=71.52999999999999
    f=-3849.5
    g=0
    h=0
    i=0
    j=3
    k=0
    l=3
    m=net.minecraft.server.v1_14_R1.DataWatcher@34c6ca0f
    n=<null>
  ]

[18:04:00] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:278) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1229) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:1089) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:770) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:851) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:977) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:451) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1142) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.addPlayer0(WorldServer.java:931) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.WorldServer.addPlayerJoin(WorldServer.java:907) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:229) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-66]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-66]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 1808.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_162]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_162]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:1.8.0_162]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_162]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_162]
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
[18:04:00] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutEntityMetadata@5227d66c[
    a=1808
    b=[net.minecraft.server.v1_14_R1.DataWatcher$Item@6a7482ee, net.minecraft.server.v1_14_R1.DataWatcher$Item@cee83b, net.minecraft.server.v1_14_R1.DataWatcher$Item@2dadc9f, net.minecraft.server.v1_14_R1.DataWatcher$Item@6ea2fe1e, net.minecraft.server.v1_14_R1.DataWatcher$Item@200f72d6, net.minecraft.server.v1_14_R1.DataWatcher$Item@5777c9dc, net.minecraft.server.v1_14_R1.DataWatcher$Item@39dc989, net.minecraft.server.v1_14_R1.DataWatcher$Item@7a3695ea, net.minecraft.server.v1_14_R1.DataWatcher$Item@21f4d1b8, net.minecraft.server.v1_14_R1.DataWatcher$Item@48a4d573, net.minecraft.server.v1_14_R1.DataWatcher$Item@25989c6f, net.minecraft.server.v1_14_R1.DataWatcher$Item@6b4fc4f3, net.minecraft.server.v1_14_R1.DataWatcher$Item@6c31a133, net.minecraft.server.v1_14_R1.DataWatcher$Item@2d0ee8b, net.minecraft.server.v1_14_R1.DataWatcher$Item@634a615a, net.minecraft.server.v1_14_R1.DataWatcher$Item@7637599c, net.minecraft.server.v1_14_R1.DataWatcher$Item@17ee5650, net.minecraft.server.v1_14_R1.DataWatcher$Item@124f5690, net.minecraft.server.v1_14_R1.DataWatcher$Item@223fb532, net.minecraft.server.v1_14_R1.DataWatcher$Item@6e08e350]
  ]

**Comment by filoghost** [comment]
Update Citizens, Holographic Displays and Protocol Lib to the latest dev builds.

**Comment by filoghost** [comment]
To follow the fix of this issue, see #135
