### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by Xge21** [filoghost/HolographicDisplays#164]
I tried to delete a hologram with an item line. (hologram.delete())

spigot-1.14.2
HolographicDisplaysAPI-2.3.3-SNAPSHOT.jar

```Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Exception ticking world
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1070) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSItem tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSItem is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3caa0413; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
        at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSItem.getBukkitEntity(EntityNMSItem.java:159) ~[?:?]
        at net.minecraft.server.v1_14_R1.Entity.removePassenger(Entity.java:1946) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.Entity.stopRiding(Entity.java:1891) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:341) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        ... 4 more
Cause of unexpected exception was
java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSItem tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSItem is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3caa0413; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
        at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSItem.getBukkitEntity(EntityNMSItem.java:159) ~[?:?]
        at net.minecraft.server.v1_14_R1.Entity.removePassenger(Entity.java:1946) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.Entity.stopRiding(Entity.java:1891) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:341) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```
and
```
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1098) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.WorldServer.removePlayer(WorldServer.java:1117) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:411) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1383) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.PlayerConnection.disconnect(PlayerConnection.java:264) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.PlayerList.shutdown(PlayerList.java:1009) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:686) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:695) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:842) [spigot-1.14.2.jar:git-Spigot-df0eb25-9e95da1]
```

**Comment by Xge21** [comment]
And
```Caused by: java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity```

**Comment by filoghost** [comment]
Update to the latest dev build please.
