### ISSUE TITLE
Editing Holograms

### ISSUE THREAD

**Issue by NightIGhost** [filoghost/HolographicDisplays#166]
When i do "/holo edit hologram"
it say "An internal error occured while attempting to perform this command"
My server is 1.8 CraftBukkit

**Comment by filoghost** [comment]
Version of the plugin? Can you paste the error on the console (on pastebin if possible)?

**Comment by NightIGhost** [comment]
[12:55:52] [Server thread/INFO]: NightIGhost issued server command: /holo edit welcome 
[12:55:52] [Server thread/ERROR]: null 
org.bukkit.command.CommandException: Unhandled exception executing command 'holo' in plugin HolographicDisplays v2.3.2 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Bukkit-7019900] 
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[minecraft_server.jar:git-Bukkit-7019900] 
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Bukkit-7019900] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202] 
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [minecraft_server.jar:git-Bukkit-7019900] 
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [minecraft_server.jar:git-Bukkit-7019900] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202] 
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot; 
at com.gmail.filoghost.holographicdisplays.commands.main.subs.EditCommand.execute(EditCommand.java:80) ~[?:?] 
at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:107) ~[?:?] 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Bukkit-7019900] 
... 14 more

**Comment by filoghost** [comment]
Use Spigot instead of CraftBukkit.
