### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Yolotroll101** [filoghost/HolographicDisplays#171]
Problem: Running any Holographic Display command such as `/hologram help` it says an internal error has occurred.

Logged event of command issue:
```
[20:17:33] [Server thread/INFO]: Yolotroll101 issued server command: /hologram help
--
128 | [20:17:33] [Server thread/ERROR]: null
129 | org.bukkit.command.CommandException: Unhandled exception executing command 'hologram' in plugin HolographicDisplays v2.3.2
130 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[minecraft_server.jar:git-Bukkit-dfa7583]
131 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[minecraft_server.jar:git-Bukkit-dfa7583]
132 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:684) ~[minecraft_server.jar:git-Bukkit-dfa7583]
133 | at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1570) ~[minecraft_server.jar:git-Bukkit-dfa7583]
134 | at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1424) ~[minecraft_server.jar:git-Bukkit-dfa7583]
135 | at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[minecraft_server.jar:git-Bukkit-dfa7583]
136 | at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[minecraft_server.jar:git-Bukkit-dfa7583]
137 | at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Bukkit-dfa7583]
138 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
139 | at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
140 | at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Bukkit-dfa7583]
141 | at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:839) [minecraft_server.jar:git-Bukkit-dfa7583]
142 | at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [minecraft_server.jar:git-Bukkit-dfa7583]
143 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [minecraft_server.jar:git-Bukkit-dfa7583]
144 | at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [minecraft_server.jar:git-Bukkit-dfa7583]
145 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
146 | Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
147 | at com.gmail.filoghost.holographicdisplays.commands.main.subs.HelpCommand.execute(HelpCommand.java:74) ~[?:?]
148 | at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:107) ~[?:?]
149 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Bukkit-dfa7583]
150 | ... 15 more
```
[Screenshot of the error](https://imgur.com/a/cHP859N)

**Comment by filoghost** [comment]
Use Spigot, not CraftBukkit.
