### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by xKenn12** [filoghost/HolographicDisplays#175]
[WARNING] [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.

java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()

at java.lang.Class.newNoSuchMethodException(Class.java:562) ~[?:1.8.0_212]

at java.lang.Class.throwExceptionOrReturnNull(Class.java:1195) ~[?:1.8.0_212]

at java.lang.Class.getMethodHelper(Class.java:1259) ~[?:1.8.0_212]

at java.lang.Class.getDeclaredMethod(Class.java:931) ~[?:1.8.0_212]

at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) [HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.nms.v1_8_R3.EntityNMSArmorStand.getId(EntityNMSArmorStand.java:143) [HolographicDisplays.jar:?]

at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:104) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:83) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.World.a(World.java:1066) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:970) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at com.gmail.filoghost.holographicdisplays.nms.v1_8_R3.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:119) [HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.nms.v1_8_R3.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:93) [HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) [HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) [HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) [HolographicDisplays.jar:?]

at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) [HolographicDisplays.jar:?]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by xKenn12** [comment]
I need help with this error on my console.

**Comment by filoghost** [comment]
Please update Holographic Displays to the latest development build, this issue has already been solved.

Development builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays

**Comment by xKenn12** [comment]
Thanks
