### ISSUE TITLE
CraftTextLine cannot be cast to CraftHologramLine

### ISSUE THREAD

**Issue by successed** [filoghost/HolographicDisplays#177]
```
[15:26:57 WARN]: java.lang.ClassCastException: com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine cannot be cast to com.gmail.filoghost.holographicdisplays.object.line.CraftHologramLine
[15:26:57 WARN]:        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.despawnEntities(CraftHologram.java:310)
[15:26:57 WARN]:        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:284)
[15:26:57 WARN]:        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:246)
[15:26:57 WARN]:        at com.gmail.filoghost.holographicdisplays.commands.main.subs.ReloadCommand.execute(ReloadCommand.java:95)
[15:26:57 WARN]:        at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:115)
[15:26:57 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:26:57 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:26:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979)
[15:26:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912)
[15:26:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by filoghost** [comment]
To this day I still don't know what caused this. CraftTextLine has always been a subclass of CraftHologramLine, and since it wasn't reported more I assume it was some classloader issues, e.g. another plugin replacing that class.
