### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by eero619** [filoghost/HolographicDisplays#179]
[ERROR] Could not load 'plugins/HolographicDisplaysAPI-2.3.3-SNAPSHOT.jar' in folder 'plugins'

org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:137) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:349) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

... 6 more

**Comment by eero619** [comment]
And also this one.

[ERROR] [HolographicDisplays] Unhandled exception number 128 occured in onPacketSending(PacketEvent) for HolographicDisplays

java.lang.RuntimeException: Cannot retrieve entity from ID.

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]

at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]

at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]

at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]

at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]

at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]

at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]

at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1423) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1396) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.broadcast(PlayerChunkMap.java:1105) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker$$Lambda$3074.00000000B59C92C0.accept(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:349) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:317) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:165) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:971) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:384) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:281) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 422.

at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]

... 36 more

Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={

fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}],

methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]

}}

at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]

at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]

at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]

at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]

... 36 more

**Comment by eero619** [comment]
and this.

[ERROR] [HolographicDisplays] Unhandled exception number 1024 occured in onPacketSending(PacketEvent) for HolographicDisplays

java.lang.RuntimeException: Cannot retrieve entity from ID.

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]

at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]

at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]

at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntity.getEntity(WrapperPlayServerSpawnEntity.java:123) ~[?:?]

at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntity.getEntity(WrapperPlayServerSpawnEntity.java:132) ~[?:?]

at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:158) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]

at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]

at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]

at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1423) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1396) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.EntityTrackerEntry$$Lambda$3589.00000000B72B3580.accept(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:242) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1168) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:813) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:439) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1014) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3550.0000000088079770.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:874) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 55.

at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]

... 43 more

Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={

fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}],

methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]

}}

at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]

at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]

at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]

at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]

... 43 more

**Comment by JonMagon** [comment]
I have the same problem.

**Comment by Zweisicht** [comment]
Hey @eero619,

I had the same issue. You have to use the latest dev build of ProtocolLib. 
https://www.spigotmc.org/resources/protocollib.1997/
