### ISSUE TITLE
NoSuchMethodError on Spigot 1.14.4

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#189]
Spigot 1.14.4
HolographicDisplays v2.3.3-b84

On server start-up
```
[17:07:53] [Server thread/ERROR]: Error occurred while enabling HolographicDisplays v2.3.3-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityTypes.<init>(Lnet/minecraft/server/v1_14_R1/EntityTypes$b;Lnet/minecraft/server/v1_14_R1/EnumCreatureType;ZZZLcom/mojang/datafixers/types/Type;Lnet/minecraft/server/v1_14_R1/EntitySize;)V
        at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:64) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.setup(NmsManagerImpl.java:52) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:124) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar-2019-07-19-1706:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by successed** [comment]
[09:11:19] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.3.3-SNAPSHOT
[09:11:19] [Server thread/ERROR]: Error occurred while enabling HolographicDisplays v2.3.3-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityTypes.<init>(Lnet/minecraft/server/v1_14_R1/EntityTypes$b;Lnet/minecraft/server/v1_14_R1/EnumCreatureType;ZZZLcom/mojang/datafixers/types/Type;Lnet/minecraft/server/v1_14_R1/EntitySize;)V
	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:64) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.setup(NmsManagerImpl.java:52) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:871) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[09:11:19] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.3.3-SNAPSHOT

**Comment by Darkweasam** [comment]
I got exactly the same issue as the 2nd guy

**Comment by Pyario** [comment]
same errors ..

**Comment by marvinej** [comment]
Same

**Comment by andris155** [comment]
Same error

**Comment by sixamscrew** [comment]
Same for me

**Comment by filoghost** [comment]
Should be fixed in https://github.com/filoghost/HolographicDisplays/commit/467fe7493e0f572eed366ef727553d1597aba893, use the new dev build.

**Comment by SlimeDog** [comment]
Confirmed fixed in b85. Thanks.

**Comment by Laukage** [comment]
where does one find dev builds? do i have to build them on my own?
