### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by a924405813** [filoghost/HolographicDisplays#190]
[20:09:33 ERROR]: [HolographicDisplays] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1494) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:391) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:351) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:199) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:1177) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:521) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:415) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:266) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1204) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-136]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-136]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 144.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 34 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}],
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
        ... 34 more

**Comment by filoghost** [comment]
Please update ProtocolLib to the latest development build, you're using an old build and that particular bug has been fixed.

ProtocolLib dev builds: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
