### ISSUE TITLE
Plugin does not load on 1.14.4

### ISSUE THREAD

**Issue by brjedi** [filoghost/HolographicDisplays#194]
No errors that I can find, plugin just simply doesn't load on 1.14.4 using the latest build.

**Comment by hornta** [comment]
You sure you used the dev build?

**Comment by brjedi** [comment]
I am using
HolographicDisplays-2.3.3-SNAPSHOT.jar
Which is the latest version I can find, at https://ci.codemc.org/job/filoghost/job/HolographicDisplays/ (Build 85)

**Comment by morfie78** [comment]
I'm experiencing the same issue on my server.  No errors, just doesn't load.  Same jar as above.

**Comment by morfie78** [comment]
I have the same issue on my server. The plugin loads, but when I run any command it gives me an error:
"An internal error occurred while attempting to perform this command"

The log shows:
[Wed, 31. Jul 2019 18:09:42 EDT INFO] FenixFire613 issued server command: /holographicdisplays:hd
[Wed, 31. Jul 2019 18:09:42 EDT ERROR] null

And that's it.

**Comment by morfie78** [comment]
More info:
14449:[18:24:40] [Server thread/ERROR]: Error occurred while enabling HolographicDisplays v2.3.3-SNAPSHOT (Is it up to date?)
14451:  at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:64) ~[?:?]
14452:  at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.NmsManagerImpl.setup(NmsManagerImpl.java:52) ~[?:?]
14453:  at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:124) ~[?:?]
14478:[18:24:40] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.3.3-SNAPSHOT

**Comment by Skynzor** [comment]
The Plugin states when it's booted in the server console:

[15:20:33 INFO]: ******************************************************
[15:20:33 INFO]:      This version of HolographicDisplays only
[15:20:33 INFO]:      works on server versions from 1.8 to 1.13.1.
[15:20:33 INFO]:      The plugin will be disabled.
[15:20:33 INFO]: ******************************************************

So yes, it doesn't work on 1.14.4.

**Comment by morfie78** [comment]
Firstly, we are using the 1.14.4 development build advertised on the main page for this plugin: http://puu.sh/E1AA6/52e5a9b1fc.png
Secondly, other people seem to have it working on 1.14.4.
Lastly, the plugin I'm using does not display what you pasted above in my console, and the plugin is not disabled.

**Comment by filoghost** [comment]
The error is incomplete, however I suspect you're using an old build. It's similar to a fixed bug and that line (64) is empty in the source code.

**Comment by josh-tf** [comment]
Having this same issue, PaperMC Build 1.7.2 (MC 1.14.4)

Someone mentioned above this was working on PaperMC and JDK12, have tried JDK8, 11 and installed 12 however getting the same error.

```
[09:38:25] [Server thread/ERROR]: Could not load 'plugins/HolographicDisplays-2.3.3-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-172]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:171) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.14.4.jar:git-Paper-172]
	at com.gmail.filoghost.holographicdisplays.HolographicDisplays.<init>(HolographicDisplays.java:51) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
	at java.lang.Class.newInstance(Class.java:590) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-172]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:174) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.14.4.jar:git-Paper-172]
	at com.songoda.epicspawners.EpicSpawners.<init>(EpicSpawners.java:56) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
	at java.lang.Class.newInstance(Class.java:590) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.14.4.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-172]
	... 6 more
```

**Comment by filoghost** [comment]
@josh-tf you may have multiple copies of the plugin in your plugins folder.

**Comment by morfie78** [comment]
Why is this closed?  @josh-tf  isn't the Original Poster, and @brjedi 's problem still exists.

**Comment by filoghost** [comment]
Original poster hasn't answered anymore. For your issue, I said:
> I suspect you're using an old build. It's similar to a fixed bug and that line (64) is empty in the source code.
and I assumed you had solved the issue.

Can you try updating to the latest 2.4.0 build?

**Comment by morfie78** [comment]
I'll try that asap and write back here.
