### ISSUE TITLE
 No API implementation set

### ISSUE THREAD

**Issue by Serekowy** [filoghost/HolographicDisplays#200]
java.lang.IllegalStateException: No API implementation set. Is Holographic Displays enabled?
    at com.gmail.filoghost.holographicdisplays.api.internal.BackendAPI.getImplementation(BackendAPI.java:36) ~[?:?]
    at com.gmail.filoghost.holographicdisplays.api.HologramsAPI.getHolograms(HologramsAPI.java:58) ~[?:?]
    at pl.minecodes.mineCase.Main.onDisable(Unknown Source) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-163]
    at pl.minecodes.mineCase.Main.onEnable(Unknown Source) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-163]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-163]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-163]
    at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-163]
    at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-163]
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-163]
    at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-163]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-163]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by filoghost** [comment]
The plugin is disabled. Check startup errors.

**Comment by Serekowy** [comment]
https://pastebin.com/KiUuUQG0
There are my logs. I don's see startup errors only this.

**Comment by filoghost** [comment]
The plugin "mineCase" doesn't depend on Holographic Displays, and is loaded before. This is fixed by adding `depend: [HolographicDisplays]` in plugin.yml.
