### ISSUE TITLE
OpenJ9 problem

### ISSUE THREAD

**Issue by DeadT1** [filoghost/HolographicDisplays#205]
**HI**

first of all, sorry for my bad english

i'm having a "problem" with the plugin after change my server to OpenJ9, i tried to update to the newest version of the plugin and still giving me the same error when i start the server, the plugin still working but it trow me this "error":

> [13:01:09 WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()
at java.lang.Class.newNoSuchMethodException(Unknown Source) ~[?:1.8.0_222]
at java.lang.Class.throwExceptionOrReturnNull(Unknown Source) ~[?:1.8.0_222]
at java.lang.Class.getMethodHelper(Unknown Source) ~[?:1.8.0_222]
at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_222]
at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) [HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.nms.v1_8_R3.EntityNMSArmorStand.getId(EntityNMSArmorStand.java:143) [HolographicDisplays230.jar:?]
at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:102) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:83) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.World.a(World.java:967) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:932) [server.jar:git-Bukkit-18fbb24]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_222]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_222]
at com.gmail.filoghost.holographicdisplays.nms.v1_8_R3.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:119) [HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.nms.v1_8_R3.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:93) [HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) [HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) [HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) [HolographicDisplays230.jar:?]
at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) [HolographicDisplays230.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [server.jar:git-Bukkit-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:680) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Bukkit-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]

i hope you can fix it or tell me how to fix it, thanks anyways for the plugin and for the work.

**Comment by sgdc3** [comment]
temp fix: disable precise movements in the plugin settings file

**Comment by filoghost** [comment]
Please update Holographic Displays to the latest development build, this issue has already been solved.

Development builds: https://ci.codemc.org/job/filoghost/job/HolographicDisplays
