### ISSUE TITLE
Command Problems in 1.8.8

### ISSUE THREAD

**Issue by DeadT1** [filoghost/HolographicDisplays#206]
Hello, i'm having a huge error in 1.8.8 with the plugin, (sorry for the bad english, i'm not american or english etc),  i hope you guys can help me with that:

> [13:24:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hd' in plugin HolographicDisplays v2.3.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Bukkit-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[server.jar:git-Bukkit-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Bukkit-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_222]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_222]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Bukkit-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: org/bukkit/entity/Player.spigot()Lorg/bukkit/entity/Player$Spigot; (loaded from file:/home/container/server.jar by sun.misc.Launcher$AppClassLoader@3f85ce4a) called from class com.gmail.filoghost.holographicdisplays.commands.main.subs.EditCommand (loaded from file:/home/container/plugins/HolographicDisplays230.jar by org.bukkit.plugin.java.PluginClassLoader@fe7c026d).
at com.gmail.filoghost.holographicdisplays.commands.main.subs.EditCommand.execute(EditCommand.java:80) ~[?:?]
at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:107) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Bukkit-18fbb24]
... 15 more

**Comment by filoghost** [comment]
Use Spigot, not just CraftBukkit.
