### ISSUE TITLE
Problems with commands not fixed

### ISSUE THREAD

**Issue by DeadT1** [filoghost/HolographicDisplays#210]
Hi, first of all, sorry for my bad English again i hope you can understand what i'm trying to say, i maked a "issue" about this before but they closed it, to clarify i'm using the version of the plugin (HolographicDisplays-2.3.3-SNAPSHOT.jar) and i'm also running Openj9 on my sv, also i'm using spigot 1.8.8 NOT craftbukkit i say this because in the last "issue" they thinked that i'm using craftbukkit but that is not true, i really hope you can help me this time, thanks for the help and sorry for the miss understanding i'm gonna leave the log here:

[03:43:47 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hd' in plugin HolographicDisplays v2.3.3-SNAPSHOT
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Bukkit-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[server.jar:git-Bukkit-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Bukkit-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_222]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_222]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [server.jar:git-Bukkit-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Bukkit-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: org/bukkit/entity/Player.spigot()Lorg/bukkit/entity/Player$Spigot; (loaded from file:/home/container/server.jar by sun.misc.Launcher$AppClassLoader@de540702) called from class com.gmail.filoghost.holographicdisplays.commands.main.subs.HelpCommand (loaded from file:/home/container/plugins/HolographicDisplays-2.3.3-SNAPSHOT.jar by org.bukkit.plugin.java.PluginClassLoader@23b83310).
at com.gmail.filoghost.holographicdisplays.commands.main.subs.HelpCommand.execute(HelpCommand.java:70) ~[?:?]
at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:115) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Bukkit-18fbb24]
... 15 more

**Comment by filoghost** [comment]
But you're not actually using the Spigot jar file, see the error logs:
`[server.jar:git-Bukkit-18fbb24]`
Instead, this is how it appears when using Spigot:
`[server.jar:git-Spigot-e4d4710-e1ebe52]`
If you have created the file with BuildTools, it produces CraftBukkit.jar and Spigot.jar, despite the fact that BuildTools is developed by Spigot's staff.

If you downloaded the file through a mirror, I recommend trying a different one.
