### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate

### ISSUE THREAD

**Issue by torpkev** [filoghost/HolographicDisplays#226]
Trying to use the Visibility Manager to hide/show by player is causing an error:

`java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.AbstractPacket.sendPacket(AbstractPacket.java:64) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.PacketHelper.sendDestroyEntitiesPacket(PacketHelper.java:121) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.sendDestroyEntitiesPacket(ProtocolLibHookImpl.java:218) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.sendDestroyPacketIfNear(CraftVisibilityManager.java:172) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.hideTo(CraftVisibilityManager.java:106) ~[?:?]`

Using ProtocolLib 4.4.0 and Holographic Displays 2.4.0

**Comment by filoghost** [comment]
This error is caused by ProtocolLib, you could have the wrong server version. What is it?

**Comment by torpkev** [comment]
You're absolutely correct.  Sorry about that - should have checked.  The official build of ProtocolLib is no good for 1.14.4 but the dev build works like a champ.
