### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by sgotfme** [filoghost/HolographicDisplays#236]
![image](https://user-images.githubusercontent.com/58674760/70403057-7d85e980-1a2d-11ea-812f-13c01a295bff.png)
when i try and do any /hd command

[02:43:26] [Server thread/INFO]: tfme issued server command: /hd help
[02:43:26] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hd' in plugin HolographicDisplays v2.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[bukkit.jar:git-Bukkit-43183ea]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit.jar:git-Bukkit-43183ea]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1590) ~[bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1444) ~[bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37) ~[bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9) ~[bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:867) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:860) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:844) [bukkit.jar:git-Bukkit-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:784) [bukkit.jar:git-Bukkit-43183ea]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
        at com.gmail.filoghost.holographicdisplays.commands.main.subs.HelpCommand.execute(HelpCommand.java:70) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:115) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[bukkit.jar:git-Bukkit-43183ea]
        ... 17 more

**Comment by RandomOofer** [comment]
Can confirm. I was wondering if I was perhaps missing something but turns out something was just broken. Here's my log: 
`[18:51:36] [Server thread/INFO]: TheSeriusGamer issued server command: /hd help
[18:51:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hd' in plugin HolographicDisplays v2.4.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Bukkit-43183ea]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Bukkit-43183ea]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1590) ~[server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1444) ~[server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37) ~[server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9) ~[server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:867) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:860) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:844) [server.jar:git-Bukkit-43183ea]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Bukkit-43183ea]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
	at com.gmail.filoghost.holographicdisplays.commands.main.subs.HelpCommand.execute(HelpCommand.java:70) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:115) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Bukkit-43183ea]
	... 17 more`

**Comment by RandomOofer** [comment]
Ah, it seems it is only the help command. /hd create works just fine

**Comment by sgotfme** [comment]
> Ah, it seems it is only the help command. /hd create works just fine

when i use /hd create it does work fine but i get the same issue with some of the other commands aswell

**Comment by filoghost** [comment]
Use the Spigot jar file, not CraftBukkit.
