### ISSUE TITLE
2.4.1 build 97 on Spigot 1.15(.1) failure

### ISSUE THREAD

**Issue by AeSix** [filoghost/HolographicDisplays#242]
You might already be aware of the issue, but if not:
```
>version
[12:58:08] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2ee05fe-d31f05f (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[12:58:08] [Server thread/INFO]: Checking version, please wait...
[12:58:08] [Thread-13/INFO]: You are running the latest version
>version HolographicDisplays
[12:58:12] [Server thread/INFO]: HolographicDisplays version 2.4.1-SNAPSHOT
```

```
[12:54:34] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_15_R1.DataWatcher exists in class PacketPlayOutSpawnEntityLiving.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getMetadata(WrapperPlayServerSpawnEntityLivi$
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:111) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:185) ~[spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:155) ~[spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1410) ~[spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1383) ~[spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:242) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1258) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1122) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:758) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:878) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1012) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:504) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.WorldServer.registerEntity(WorldServer.java:1133) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.WorldServer.addPlayer0(WorldServer.java:956) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.WorldServer.addPlayerJoin(WorldServer.java:932) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:214) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:53) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:220) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:129) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1099) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-server.jar:git-Spigot-2ee05fe-d31f05f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[12:54:34] [Server thread/ERROR]: Parameters:
  net.minecraft.server.v1_15_R1.PacketPlayOutSpawnEntityLiving@168f7e1b[
    a=46
    b=2e8f6c7e-f2d0-4418-b491-fbd7f09b50a5
    c=1
    d=-5.445
    e=65.47999999999999
    f=-5.442
    g=0
    h=0
    i=0
    j=0
    k=0
    l=0
  ]
```

Getting this with ProtocolLib build 436 and 439. 
**Without** ProtocolLib, there is no error.

**Comment by filoghost** [comment]
This also happens on 1.15, so it's not a 1.15.1 specific issue. Also, showing/hiding holograms isn't working properly with ProtocolLib.

**Comment by AeSix** [comment]
Also, I'd like to clarify, that with or without ProtocolLib, the holograms do show.  So, not sure what is affected by using, or not using ProtocolLib with HolographicDisplays.  

For my use, the holograms are 3-4 years old, and dont' get messed with, so other than the error, working perfectly fine /for me/

**Comment by filoghost** [comment]
Fixed in build 98.
