### ISSUE TITLE
Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by david890504** [filoghost/HolographicDisplays#279]
[08:26:02 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:02 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:03 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:04 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:04 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:05 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:07 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:09 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
[08:26:10 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null

**Comment by filoghost** [comment]
The error is incomplete. Spigot is cutting it because it's spamming the console, you can find the complete one at the start of your log file.

**Comment by david890504** [comment]
[12:38:14 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.4.1
java.lang.NullPointerException: null
        at com.gmail.filoghost.holographicdisplays.object.PluginHologramManager.onChunkLoad(PluginHologramManager.java:65) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.listener.MainListener.processChunkLoad(MainListener.java:97) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.listener.MainListener.onChunkLoad(MainListener.java:87) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1023.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.Chunk.loadCallback(Chunk.java:644) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$7(PlayerChunk.java:415) ~[patched_1.14.4.jar:git-Paper-243]
        at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$8(PlayerChunk.java:413) ~[patched_1.14.4.jar:git-Paper-243]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_241]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_241]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_241]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:102) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:420) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:105) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:430) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:370) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:276) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:373) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:80) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:334) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.World.getType(World.java:726) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.VoxelShapes.a(VoxelShapes.java:240) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.VoxelShapes.a(VoxelShapes.java:188) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.Entity.a(Entity.java:886) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.Entity.a(Entity.java:841) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.Entity.e(Entity.java:801) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:560) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2209) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.EntityHuman.e(EntityHuman.java:1495) ~[patched_1.14.4.jar:git-Paper-243]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.e(EntityHumanNPC.java:180) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:345) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:431) ~[?:?]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:702) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:472) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by filoghost** [comment]
I don't know what's causing it. I think you have a plugin that depends on Holographic Displays (because of the PluginHologramManager) that causes this problem, by using methods outside the API.

If you don't have know what plugin uses Holographic Displays or you have multiple, you need to guess and start removing plugins one by one until you find the one causing the error.
