### ISSUE TITLE
1.16.2 Incompatible

### ISSUE THREAD

**Issue by CirnoTH** [filoghost/HolographicDisplays#325]
### Description
Plugin is incompatible with the Spigot 1.16.2

### How to reproduce
Load the plugin in Spigot 1.16.2

### Platform
- Server version (output of `/version`): This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): HolographicDisplays v2.4.3 (https://paste.ubuntu.com/p/7ypscHZKvf/)
- ProtocolLib version, if installed (check with `/protocol version`): ProtocolLib v4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

### Additional context
https://paste.ubuntu.com/p/N9WCb3FJgg/

**Comment by Esophose** [comment]
Resolved by #324

**Comment by james-d-elliott** [comment]
Just letting you know getting this on the [snapshot of paper 1.16.2](https://cdn.discordapp.com/attachments/555469074080202765/743313314167390208/1.16.2-r2.jar):


```
[11:09:38 INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.4
[11:09:38 WARN]: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap cannot be cast to class it.unimi.dsi.fastutil.objects.Object2IntMap (it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap and it.unimi.dsi.fastutil.objects.Object2IntMap are in unnamed module of loader 'app')
[11:09:38 WARN]:      at com.gmail.filoghost.holographicdisplays.nms.v1_16_R2.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:61)
[11:09:38 WARN]:      at com.gmail.filoghost.holographicdisplays.nms.v1_16_R2.NmsManagerImpl.setup(NmsManagerImpl.java:56)
[11:09:38 WARN]:      at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:126)
[11:09:38 WARN]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:09:38 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[11:09:38 WARN]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[11:09:38 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499)
[11:09:38 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413)
[11:09:38 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[11:09:38 WARN]:      at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241)
[11:09:38 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[11:09:38 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[11:09:38 WARN]:      at java.base/java.lang.Thread.run(Unknown Source)
[11:09:38 INFO]:
[11:09:38 INFO]:
[11:09:38 INFO]: ****************************************************************************
[11:09:38 INFO]:     Holographic Displays was unable to register custom entities.
[11:09:38 INFO]:
[11:09:38 INFO]:     This plugin has been disabled.
[11:09:38 INFO]: ****************************************************************************

````

**Comment by filoghost** [comment]
Now it's solved.
