### ISSUE TITLE
Holographic Displays giving lots of Error's

### ISSUE THREAD

**Issue by StaticCraft** [filoghost/HolographicDisplays#34]
Here is the error it only occurs when I spawn into a location where there is Holographic displays

Error below

[20:18:50 ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject
        at com.comphenix.protocol.wrappers.WrappedWatchableObject.getWatcherObject(WrappedWatchableObject.java:73) ~[ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.wrappers.WrappedWatchableObject.getIndex(WrappedWatchableObject.java:81) ~[ProtocolLib.jar:4.0.2-b303]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.pre1_9.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:157) ~[HolographicDisplays.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.0.2-b303]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.0.2-b303]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:330) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.EntityTracker.updatePlayers(EntityTracker.java:176) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:789) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[20:18:50 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayOutEntityMetadata@4f8016[
    a=186
    b=[net.minecraft.server.v1_8_R1.WatchableObject@e38860, net.minecraft.server.v1_8_R1.WatchableObject@1e95eb, net.minecraft.server.v1_8_R1.WatchableObject@1774dbc, net.minecraft.server.v1_8_R1.WatchableObject@1b9f6c2, net.minecraft.server.v1_8_R1.WatchableObject@125d31d, net.minecraft.server.v1_8_R1.WatchableObject@10aa59f, net.minecraft.server.v1_8_R1.WatchableObject@2b0bef, net.minecraft.server.v1_8_R1.WatchableObject@82fcce, net.minecraft.server.v1_8_R1.WatchableObject@1447038, net.minecraft.server.v1_8_R1.WatchableObject@1fc0e52, net.minecraft.server.v1_8_R1.WatchableObject@1201fb1, net.minecraft.server.v1_8_R1.WatchableObject@5f497, net.minecraft.server.v1_8_R1.WatchableObject@ce8a5f, net.minecraft.server.v1_8_R1.WatchableObject@113900a, net.minecraft.server.v1_8_R1.WatchableObject@d5dace, net.minecraft.server.v1_8_R1.WatchableObject@101348f]

**Comment by filoghost** [comment]
Wrong ProtocolLib Version, please use an older one for 1.8

**Comment by tehrenderr** [comment]
I'm getting the same error using protocollib v4.1.0 which is meant for 1.8?

**Comment by filoghost** [comment]
Now fixed in HD v2.2.1, Protocol Lib 4.1 works on Minecraft 1.8
