### ISSUE TITLE
Right version, plugin says wrong version

### ISSUE THREAD

**Issue by STEINTALCHRIS** [filoghost/HolographicDisplays#356]
### Description

The Plugin does not start at server start because the server version is wrong

### How to reproduce

Update the plugin an start the server

### Platform

- Server version (output of `/version`): git-Paper-265 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`):  lastet
- ProtocolLib version, if installed (check with `/protocol version`):   ProtocolLib v4.5.0
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ViaVersion, ViaBackwards, ViaRewind

### Additional context

[12:31:31] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.4
[12:31:31] [Server thread/INFO]: 
[12:31:31] [Server thread/INFO]:  
[12:31:31] [Server thread/INFO]: ****************************************************************************
[12:31:31] [Server thread/INFO]:     Holographic Displays does not support this server version.
[12:31:31] [Server thread/INFO]:     Supported Spigot versions: from 1.8.3 to 1.16.
[12:31:31] [Server thread/INFO]:  
[12:31:31] [Server thread/INFO]:     This plugin has been disabled.
[12:31:31] [Server thread/INFO]: ****************************************************************************
[12:31:31] [Server thread/INFO]:  

___________________________________________________________________________________________________________________

[12:31:38] [Craft Scheduler Thread - 16/WARN]: [HolographicDisplays] Unable to check for updates: unhandled exception.
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:161) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:130) ~[patched_1.16.4.jar:git-Paper-265]
	at com.gmail.filoghost.holographicdisplays.updater.UpdateChecker.lambda$run$1(UpdateChecker.java:63) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-265]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Inxity** [comment]
Update holographic displays to v2.4.5

**Comment by filoghost** [comment]
As they said, it's not the latest version.
