### ISSUE TITLE
BUG: issue with time placeholder

### ISSUE THREAD

**Issue by carltheraveyt** [filoghost/HolographicDisplays#360]
### Description
I've been asked by the plugin issue on the console to contact the developer because of this issue.  
The placeholder {time} registered by the plugin HolographicDisplays generated an exception while updating.

### How to reproduce
idk how to explain how to replicate this issue. 

### Platform

- Server version (output of `/version`): CraftBukkit version git-Spigot-56f8471-7554e08 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): 2.4.4
- ProtocolLib version, if installed (check with `/protocol version`): 4.5.0
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ViaVersion

### Additional context
https://mcpaste.io/aeb095d067fbfafb 
i can also provide logs from today if requested.

**Comment by Drago903** [comment]
_How to reproduce

idk how to explain how to replicate this issue._

Nobody can help you because you need to reproduce the error or at least have a screen of the error to be able to see the line where the error is (I think that's why they didn't answer you)

**Comment by 9514854** [comment]
I just started having the same issue, with that same error spamming console. I recently installed HolographicExtensions, so there's a possibility that has to do with the error. It doesn't seem to be causing any functionality issues, but I don't know the fix. To restate the issue, console is being spammed with the error:

[03:23:13 WARN]: [HolographicDisplays] The placeholder {time} registered by the plugin HolographicDisplays generated an exception while updating. Please contact the author of HolographicDisplays
java.lang.NullPointerException: null
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersRegister.lambda$static$3(PlaceholdersRegister.java:50) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.placeholder.Placeholder.update(Placeholder.java:78) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersManager.lambda$load$0(PlaceholdersManager.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-352]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-352]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-352]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-352]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-352]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-352]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-352]
        at java.lang.Thread.run(Thread.java:834) [?:?]

This error appears about twice a second.

**Comment by 9514854** [comment]
The error was actually a syntax mistake I made while editing config.yml lol
