### ISSUE TITLE
Ever since I installed this plugin I have been getting this error

### ISSUE THREAD

**Issue by MetooMango** [filoghost/HolographicDisplays#419]
### What are you trying to do?
Fix an error message

### What have you tried so far?
tried checking if its caused by any conflicting plugins and the error persists

### Platform

- Server version (output of `/version`): 1.16.4 
- Holographic Displays version (check with `/hd`): 2.4.5
- ProtocolLib version, if installed (check with `/protocol version`): 4.6.0 SNAPSHOT- b492
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

### Additional context
>.... [23:16:00 ERROR]: [HolographicDisplays] Unhandled exception number 262144 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.NoClassDefFoundError: com/comphenix/net/sf/cglib/proxy/Factory
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:87) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1709) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.EntityTrackerEntry.sendPlayerPacket(EntityTrackerEntry.java:49) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:201) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.EntityTrackerEntry.tick(EntityTrackerEntry.java:75) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2052) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2063) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:856) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:734) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:460) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-414]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Andre601** [comment]
Did you try the latest dev builds (2.4.6)?
They have been build 21 days ago.

https://ci.codemc.io/job/filoghost/job/HolographicDisplays/lastSuccessfulBuild/
