### ISSUE TITLE
Exception. Async get entities

### ISSUE THREAD

**Issue by Official-DenBeKKer** [filoghost/HolographicDisplays#475]
### Description
[13:05:02] [pool-19-thread-13/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1795) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1306) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.getNMSEntityBaseFromID(NmsManagerImpl.java:139) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getNMSEntityBase(ProtocolLibHookImpl.java:308) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:299) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:291) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:94) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1708) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1694) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.sendPacket(BukkitTabPlayer.java:132) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.shared.ITabPlayer.sendPacket(ITabPlayer.java:529) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitArmorStand.spawn(BukkitArmorStand.java:139) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.api.ArmorStandManager.lambda$spawn$0(ArmorStandManager.java:42) ~[TAB-2.8.11-pre19.jar:?]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2093) ~[?:?]
        at me.neznamy.tab.api.ArmorStandManager.spawn(ArmorStandManager.java:42) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.PacketListener.lambda$onEntitySpawn$2(PacketListener.java:112) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.shared.cpu.CPUManager$2.run(CPUManager.java:116) [TAB-2.8.11-pre19.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:05:02] [pool-19-thread-13/ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityLiving@5892b562[
    a=2000000003
    b=544e20b4-8cdf-4a79-891d-b2f473dcb4c2
    c=1
    d=-1168.5
    e=69.85584062504455
    f=456.5684367541288
    g=0
    h=-627
    i=0
    j=0
    k=0
    l=-13
  ]

[13:05:02] [pool-19-thread-13/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1795) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1306) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.getNMSEntityBaseFromID(NmsManagerImpl.java:139) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getNMSEntityBase(ProtocolLibHookImpl.java:308) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:299) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:291) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:139) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1708) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1694) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.sendPacket(BukkitTabPlayer.java:132) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.shared.ITabPlayer.sendPacket(ITabPlayer.java:529) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitArmorStand.spawn(BukkitArmorStand.java:139) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.api.ArmorStandManager.lambda$spawn$0(ArmorStandManager.java:42) ~[TAB-2.8.11-pre19.jar:?]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2093) ~[?:?]
        at me.neznamy.tab.api.ArmorStandManager.spawn(ArmorStandManager.java:42) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.PacketListener.lambda$onEntitySpawn$2(PacketListener.java:112) ~[TAB-2.8.11-pre19.jar:?]
        at me.neznamy.tab.shared.cpu.CPUManager$2.run(CPUManager.java:116) [TAB-2.8.11-pre19.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:05:02] [pool-19-thread-13/ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@6d694d7b[
    a=2000000003
    b=[net.minecraft.network.syncher.DataWatcher$Item@22dc4604, net.minecraft.network.syncher.DataWatcher$Item@7dc41ac4, net.minecraft.network.syncher.DataWatcher$Item@307e8280, net.minecraft.network.syncher.DataWatcher$Item@17db0361]
  ]

### How to reproduce
join 1.17 server and teleport

### Platform

- 1.17
- 2.4.7-b168
- 4.7.0-b507
- no

**Comment by filoghost** [comment]
This is caused by an external plugin (`me.neznamy.tab`) sending async packets. Unfortunately invoking the method to obtain the entities is necessary, because Holographic Displays needs to check if an entity is related to holograms or not.

**Comment by Official-DenBeKKer** [comment]
https://github.com/NEZNAMY/TAB/issues/330#issuecomment-864392614

**Comment by filoghost** [comment]
As quick fix, I could just ignore the listener on async threads. Minecraft itself only uses the main thread, and that's the packets HD should intercept.

**Comment by Official-DenBeKKer** [comment]
Add try-catch as NEZNAMY said. Or you can check if packet async, idk how it can be implemented, but i think that you can do it...

**Comment by filoghost** [comment]
Try the latest dev build: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

I checked if the packet is async.

**Comment by Official-DenBeKKer** [comment]
It works
