### ISSUE TITLE
Plugin Crashing upon creating hologram (Spigot 1.17)

### ISSUE THREAD

**Issue by TMKCRepo** [filoghost/HolographicDisplays#476]
### Description

Typing "/hd create test test" Generates the issue in "## Additional context".

### How to reproduce

Typing "/hd create test test" Generates the issue in "## Additional context".

Compiled Spigot using SpigotMC's provided "BuildTools", installed the HolographicDisplays version "2.4.8-SNAPSHOT-b173" from Githubs "releases" section and started the server.  Starting the server gives no errors for the plugin.  Running the command to create a hologram generates the issue-

### Platform
- Server version (output of `/version`):  1.17-R0.1-SNAPSHOT (3124-Spigot-66f9d3c-384e117 MC 1.17)
- Holographic Displays version (check with `/hd`):  2.4.8-SNAPSHOT-b173
- ProtocolLib version, if installed (check with `/protocol version`):  4.7.0-SNAPSHOT-b507
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):  No

### Additional context

[19:08:35] [Server thread/INFO]: KaySeeYT issued server command: /hd create test test
[19:08:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hd' in plugin HolographicDisplays v2.4.8-SNAPSHOT-b173
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1100) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl tried to access private field net.minecraft.server.level.WorldServer.G (com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1c3cc21e; net.minecraft.server.level.WorldServer is in unnamed module of loader 'app')
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:94) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:74) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:102) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:294) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:241) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.subs.CreateCommand.execute(CreateCommand.java:86) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:117) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:3124-Spigot-66f9d3c-384e116]
        ... 19 more

**Comment by filoghost** [comment]
Try updating Spigot to the latest build.
