### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zlAquiles** [filoghost/HolographicDisplays#478]
### Description
when I create a hologram /hd create when creating it works perfectly, but there is that error in the console

### How to reproduce
create any hologram

### Platform
- Server version (output of `/version`):  1.17 - 3149-Spigot-101ebb6-9122f5a (MC: 1.17)
- Holographic Displays version (check with `/hd`): v2.4.8-SNAPSHOT-b173
- ProtocolLib version, if installed (check with `/protocol version`): v4.7.0-SNAPSHOT-b510
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): NO

### Additional context
Craft Scheduler Thread - 15/ERROR]: [HolographicDisplays] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1795) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1306) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.getNMSEntityBaseFromID(NmsManagerImpl.java:121) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getNMSEntityBase(ProtocolLibHookImpl.java:308) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:299) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:291) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:139) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1708) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1694) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at dev.rosewood.rosestacker.nms.v1_17_R1.NMSHandlerImpl.updateEntityNameTagVisibilityForPlayer(NMSHandlerImpl.java:283) ~[?:?]
        at dev.rosewood.rosestacker.stack.StackingThread.processNametags(StackingThread.java:247) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by filoghost** [comment]
Please try the latest dev build: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
