### ISSUE TITLE
Error on paper dev builds (method bw)

### ISSUE THREAD

**Issue by MrJarousek** [filoghost/HolographicDisplays#480]
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 

### Additional context

[09:43:25] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.7-SNAPSHOT-b168
[09:43:25] [Server thread/WARN]: java.lang.NoSuchFieldException: bw
[09:43:25] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[09:43:25] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectField.init(ReflectField.java:34)
[09:43:25] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectField.get(ReflectField.java:40)
[09:43:25] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:58)
[09:43:25] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.setup(NmsManagerImpl.java:53)
[09:43:25] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:126)
[09:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:43:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[09:43:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[09:43:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[09:43:25] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303)
[09:43:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[09:43:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:43:25] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[09:43:25] [Server thread/INFO]: 
[09:43:25] [Server thread/INFO]:  
[09:43:25] [Server thread/INFO]: ****************************************************************************
[09:43:25] [Server thread/INFO]:     Holographic Displays was unable to register custom entities.
[09:43:25] [Server thread/INFO]:  
[09:43:25] [Server thread/INFO]:     This plugin has been disabled.
[09:43:25] [Server thread/INFO]: ****************************************************************************
[09:43:25] [Server thread/INFO]:

**Comment by filoghost** [comment]
Try the latest dev build: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/
