### ISSUE TITLE
Spam in console with placeholder {time}.

### ISSUE THREAD

**Issue by the5gi** [filoghost/HolographicDisplays#491]
### Confirmation

- [x] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Hello, I'm experiencing an issue with the plugin. I'm running Sugarcane version git-Sugarcane-"7a5f1f6" (MC: 1.17), I am not sure whether or not this is a sugarcane issue or a Holographic Displays Issue. I'm sorry if it is sugarcane and that's where I'm going next. The error I'm getting is linked below. This doesn't lower my expectations of the plugin and I still really like it. I just wish to know if this will ever be fixed or not. Thanks!

`[22:18:49 WARN]: [HolographicDisplays] The placeholder {time} registered by the plugin HolographicDisplays generated an exception while updating. Please contact the author of HolographicDisplays
java.lang.NullPointerException: Cannot invoke "java.text.SimpleDateFormat.format(java.util.Date)" because "com.gmail.filoghost.holographicdisplays.disk.Configuration.timeFormat" is null
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersRegister.lambda$static$3(PlaceholdersRegister.java:50) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.placeholder.Placeholder.update(Placeholder.java:78) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersManager.lambda$load$0(PlaceholdersManager.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1259) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

### How to reproduce

1. Goto https://github.com/SugarcaneMC/Sugarcane/actions/runs/972729848 and download the zip at the bottom of the screen.

2. Do the normal server jar startup procedure and place the plugin in the plugins folder.

3. Startup the server and create one or two holograms.

4. Startup the server and see the error.

(NOTE: The 3rd step is optional but the error occurred after I did step 3)

### Server version

This server is running Sugarcane version git-Sugarcane-"7a5f1f6" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Holographic Displays version

Holographic Displays v2.4.8

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, ViaRewind.

**Comment by filoghost** [comment]
Fixed in v3 beta.
