### ISSUE TITLE
Help please,not working

### ISSUE THREAD

**Issue by RebornLGN** [filoghost/HolographicDisplays#496]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

[16:56:56] [Server thread/INFO]: RebornLGN issued server command: /hologram create we we
[16:56:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hologram' in plugin HolographicDisplays v2.4.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl tried to access private field net.minecraft.server.level.WorldServer.G (com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @22be4709; net.minecraft.server.level.WorldServer is in unnamed module of loader 'app')
	at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:94) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:74) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:102) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:294) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:241) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.subs.CreateCommand.execute(CreateCommand.java:86) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:117) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.jar:3124-Spigot-66f9d3c-384e116]

### Holographic Displays version

HolographicDisplays v2.4.8

**Comment by filoghost** [comment]
Please try the new v3 beta version. This bug was fixed.
