### ISSUE TITLE
[10:06:13 WARN]: [HolographicPlaceholders] Plugin HolographicPlaceholders v2.1.2 Stable generated an exception while executing task 1652

### ISSUE THREAD

**Issue by yuankun1** [filoghost/HolographicDisplays#501]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

[10:06:13 WARN]: [HolographicPlaceholders] Plugin HolographicPlaceholders v2.1.2 Stable generated an exception while executing task 1652
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1842) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.neutralplasma.holographicPlaceholders.addons.baltop.BalTopAddonV2$2.run(BalTopAddonV2.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-91]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-91]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### How to reproduce

no

### Server version

paper91 1.17.1-P0.1-SNAOSHOT

### Holographic Displays version

2.4.8

### ProtocolLib version (if installed)

4.7.0-SNAPSHOT-b528

### Installed plugins that allow players to join with multiple Minecraft versions

NEW

**Comment by filoghost** [comment]
This is not caused by Holographic Displays, but by HolographicPlaceholders.
