### ISSUE TITLE
Unhandled exception executing command 'hologram' in plugin

### ISSUE THREAD

**Issue by SimaKyr** [filoghost/HolographicDisplays#505]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

My hologram don't displays and says error.

### How to reproduce

Execute command:
`/hologram create portalCreative &3Портал в мир &l&aКреатив`

### Server version

This server is running Paper version git-Paper-107 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5a9c14b) You are running the latest version

### Holographic Displays version

2.4.8

### ProtocolLib version (if installed)

v4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards, GeyserMC

### Additional information

```java
[15:59:49] [Server thread/INFO]: SimaKyr issued server command: /hologram create portalCreative &3Портал в мир &l&aКреатив
--
930 | [15:59:52] [Server thread/ERROR]: null
931 | org.bukkit.command.CommandException: Unhandled exception executing command 'hologram' in plugin HolographicDisplays v2.4.8
932 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-Paper-107]
933 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[minecraft_server.jar:git-Paper-107]
934 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[minecraft_server.jar:git-Paper-107]
935 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2180) ~[?:?]
936 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1991) ~[?:?]
937 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1972) ~[?:?]
938 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
939 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
940 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
941 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft_server.jar:git-Paper-107]
942 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
943 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
944 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[minecraft_server.jar:git-Paper-107]
945 | at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[minecraft_server.jar:git-Paper-107]
946 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
947 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[minecraft_server.jar:git-Paper-107]
948 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[minecraft_server.jar:git-Paper-107]
949 | at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
950 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[minecraft_server.jar:git-Paper-107]
951 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[minecraft_server.jar:git-Paper-107]
952 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[minecraft_server.jar:git-Paper-107]
953 | at java.lang.Thread.run(Thread.java:831) [?:?]
954 | Caused by: java.lang.OutOfMemoryError: Metaspace


```

**Comment by Deathinflames** [comment]
> Caused by: java.lang.OutOfMemoryError: Metaspace

This is not an issue with the Holographic Displays plugin. You've simply exceeded the amount of memory available to your server. Either allocate more RAM to your server or remove other plugins using a lot of memory.
