### ISSUE TITLE
Shutdown spam still happening.

### ISSUE THREAD

**Issue by andrewkm** [filoghost/HolographicDisplays#507]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

```
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
```

### How to reproduce

Shut down server.

### Server version

paper 1.16.5 Build 783

### Holographic Displays version

Jenkins Build 179

### ProtocolLib version (if installed)

Jenkins Build 530

**Comment by TheRealRyGuy** [comment]
fixed in #512

**Comment by electronicboy** [comment]
```
[23:06:07 ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[23:06:07 INFO]: Craft Scheduler Thread - 13: still running
[23:06:07 INFO]: 	at java.base@16.0.1/sun.nio.ch.Net.connect0(Native Method)
[23:06:07 INFO]: 	at java.base@16.0.1/sun.nio.ch.Net.connect(Net.java:576)
[23:06:07 INFO]: 	at java.base@16.0.1/sun.nio.ch.Net.connect(Net.java:565)
[23:06:07 INFO]: 	at java.base@16.0.1/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[23:06:07 INFO]: 	at java.base@16.0.1/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[23:06:07 INFO]: 	at java.base@16.0.1/java.net.Socket.connect(Socket.java:645)
[23:06:07 INFO]: 	at java.base@16.0.1/java.net.Socket.connect(Socket.java:595)
[23:06:07 INFO]: 	at java.base@16.0.1/java.net.Socket.<init>(Socket.java:519)
[23:06:07 INFO]: 	at java.base@16.0.1/java.net.Socket.<init>(Socket.java:293)
[23:06:07 INFO]: 	at com.gmail.filoghost.holographicdisplays.bridge.bungeecord.serverpinger.ServerPinger.fetchData(ServerPinger.java:36)
[23:06:07 INFO]: 	at com.gmail.filoghost.holographicdisplays.bridge.bungeecord.BungeeServerTracker.lambda$startTask$0(BungeeServerTracker.java:168)
[23:06:07 INFO]: 	at com.gmail.filoghost.holographicdisplays.bridge.bungeecord.BungeeServerTracker$$Lambda$6615/0x0000000801f7ea38.run(Unknown Source)
[23:06:07 INFO]: 	at app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:06:07 INFO]: 	at app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:06:07 INFO]: 	at app//com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:06:07 INFO]: 	at java.base@16.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[23:06:07 INFO]: 	at java.base@16.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[23:06:07 INFO]: 	at java.base@16.0.1/java.lang.Thread.run(Thread.java:831)
```

I forgot to cover an area in paper with these debug logs, but, bearing in mind that this is from a server in a debug environment mirroring a real server, so, not all servers defined in the config exist, so, this issue is somewhat more pronounced and there are likely more areas where this catches up

Basically, when a plugin is disabled, onDisable is called, and then tasks and events, etc, are cancelled and unregistered, existing tasks in the thread pool will still be running, these tasks generally have 5 seconds to clean up and close their doors, easiest solution imho is gonna be to just shove these tasks into a thread pool, be that one the server creates or the common ForkJoinPool

**Comment by filoghost** [comment]
I'm sorry, as part of the switch to maintenance-only mode (read [here](https://dev.bukkit.org/projects/holographic-displays/files/4507130) for more info), I'm closing this as it's just a log message that causes no harm. The fix is not trivial.
