### ISSUE TITLE
ChunkLoadEvent error

### ISSUE THREAD

**Issue by renzotom** [filoghost/HolographicDisplays#51]
I reported that bug also on bukkit, here is it:
`[11:11:20] [Thread-316470/ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.2.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.Chunk.loadNearby(Chunk.java:910) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:131) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:95) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:561) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.Location.getBlock(Location.java:87) [spigot.jar:git-Spigot-b32c8f8-46226d6]
	at tw.mics.spigot.plugin.nomoreesp.runnable.CheckXRayRunnable.run(CheckXRayRunnable.java:48) [NoMoreESP.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Async entity add
	at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:13) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_11_R1.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:101) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.nms.v1_11_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:94) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:75) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:300) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.NamedHologramManager.onChunkLoad(NamedHologramManager.java:49) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.listener.MainListener.onChunkLoad(MainListener.java:63) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-b32c8f8-46226d6]
	... 18 more`

**Comment by filoghost** [comment]
It's caused by this plugin: https://www.spigotmc.org/resources/nomoreesp.25518
That said, I should probably introduce a better error handling.

**Comment by renzotom** [comment]
And when you think, it will be done?

**Comment by filoghost** [comment]
Done. No more errors, now Holographic Displays should handle this situation https://github.com/filoghost/HolographicDisplays/commit/d6f7da4e74423d6577e5bf7e686cfee1b837d2d2
