### ISSUE TITLE
Need 1.18 support urgently

### ISSUE THREAD

**Issue by kalleswe** [filoghost/HolographicDisplays#529]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Plugin does not load in 1.18. Need 1.18 API support in the code.
Please fix asap!

### How to reproduce

1. Load plugin
2. Plugin load fails due to unsupported version.

### Server version

1.18

### Holographic Displays version

latest

### ProtocolLib version (if installed)

latest

### Installed plugins that allow players to join with multiple Minecraft versions

none

**Comment by filoghost** [comment]
I will publish soon a beta version of the v3 branch on Bukkit Dev.

**Comment by sugonmad** [comment]
> I will publish soon a beta version of the v3 branch on Bukkit Dev.

Just curious and desperate: How soon? I wanted to launch my server tomorrow and I need this, too. If it takes a while, also okay, just wanted to ask how long. Sorry.

**Comment by hoehoetvhss** [comment]
> Just curious and desperate: How soon? I wanted to launch my server tomorrow and I need this, too. If it takes a while, also okay, just wanted to ask how long. Sorry.

It's the same that we're all waiting for 1.18 support. But plug-in developers will be working hard to support 1.18.

Urging may not see good results, so we just have to wait.

**Comment by TenReeez** [comment]
HD works on 1.18, but upon every server reboot, you need to do /hd reload

**Comment by hoehoetvhss** [comment]
`
[15:07:35 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'hd' in plugin HolographicDisplays v2.4.9 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2012) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1993) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-32]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        `

**Comment by Budderman18** [comment]
> HD works on 1.18, but upon every server reboot, you need to do /hd reload

It does not work. The plugin disables itself on startup

**Comment by hoehoetvhss** [comment]
> > HD works on 1.18, but upon every server reboot, you need to do /hd reloadHD는 1.18에서 작동하지만 서버를 재부팅할 때마다 /HD 재로드 작업을 수행해야 함
> 
> It does not work.그것은 효과가 없다. The plugin disables itself on startup 시작할 때 플러그인이 자체 실행 중지됨

There is currently no way we can do it, and it is our best way to release a beta version of the plug-in that supports 1.18.

**Comment by filoghost** [comment]
A beta version was submitted yesterday on Bukkit Dev, it should be out tomorrow.

**Comment by HugoDu3** [comment]
> A beta version was submitted yesterday on Bukkit Dev, it should be out tomorrow.

Can you update it on https://ci.codemc.io/job/filoghost/job/HolographicDisplays/ so we can download it ? Because my server opens today

**Comment by sugonmad** [comment]
> A beta version was submitted yesterday on Bukkit Dev, it should be out tomorrow.

Thank you so much!

**Comment by filoghost** [comment]
It hasn't been approved yet for some reason. Maybe since the code has changed a lot, they need more time.

**Comment by kevincolyer** [comment]
Thanks for the hard work. It is appreciated!

**Comment by baailey** [comment]
Are you able to upload a dev build to your CodeMC project? Or link a download here?

**Comment by baailey** [comment]
Bukkit has approved the new version, nvm

**Comment by filoghost** [comment]
Nice, I'll close this and prepare for the flood of new bug reports.
