### ISSUE TITLE
HologramDisplays Error while decoding player count from Bungee

### ISSUE THREAD

**Issue by FootClick** [filoghost/HolographicDisplays#537]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

HologramDisplays Error while decoding player count from Bungee

[20:51:31] [Server thread/WARN]: [HolographicDisplays] Error while decoding player count from BungeeCord.
java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340) ~[?:1.8.0_312]
	at java.io.DataInputStream.readUTF(DataInputStream.java:589) ~[?:1.8.0_312]
	at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_312]
	at me.filoghost.holographicdisplays.plugin.bridge.bungeecord.BungeeMessenger.onPluginMessageReceived(BungeeMessenger.java:61) [HolographicDisplays.jar:3.0.0-SNAPSHOT]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:429) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2154) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

### Holographic Displays version

HolographicDisplays version v3.0.0-SNAPSHOUT

**Comment by elpixis** [comment]
I have the same problem on my server, did you find the solution?

**Comment by FootClick** [comment]
> 

No

**Comment by FootClick** [comment]
> 我的服务器也有同样的问题，请问您有解决方案吗？

I used it back v2.4.9

**Comment by partydragen** [comment]
I have the same problem with latest version v3.0.0 i changed both server version to 1.18 and to java-17 and latest version v3, does not work with latest development build either :/

**Comment by Cyber24-Dr** [comment]
I have the same Issue in the v3.0.0

**Comment by partydragen** [comment]
Any update on this? its very spammy!

**Comment by Cyber24-Dr** [comment]
it is not only in the 3.0 but also with me in the 2.4.9

**Comment by FootClick** [comment]
emm My 2.4.9 running well

**Comment by partydragen** [comment]
2.4.9 works for me too, just the latest v3 with spams that error

**Comment by Cyber24-Dr** [comment]
I have the normal 2.4.9 was downloadet from the Bukkit site, and on my lobby i have no problems. only on the cb have the problem

**Comment by elmaslarry** [comment]
[HolographicDisplays] Error while decoding player count from BungeeCord.
java.io.EOFException: null

Same error for me on 3.0

**Comment by partydragen** [comment]
Looks like latest development build fixed the issue, I believe its this commit https://github.com/filoghost/HolographicDisplays/commit/2d177edced1a435a2be99971dff7930424e48486
