### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by HooohoGames** [filoghost/HolographicDisplays#543]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

In my console I keep getting this pop up < [10:28:47 WARN]: [HolographicDisplays] Could not detect PacketPlayOutEntityDestroy details, error can be ignored if on Minecraft 1.17.1+
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/it/unimi/dsi/fastutil/ints/IntList
        at me.filoghost.holographicdisplays.nms.v1_17_R1.PacketHelper.useEntityListDestroyPacket(PacketHelper.java:41) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.nms.v1_17_R1.PacketHelper.<clinit>(PacketHelper.java:18) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.nms.v1_17_R1.VersionTextNMSPacketEntity.newDestroyPackets(VersionTextNMSPacketEntity.java:67) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.plugin.hologram.tracking.TextLineTracker.sendDestroyPackets(TextLineTracker.java:95) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.plugin.hologram.tracking.LineTracker.modifyViewersAndSendPackets(LineTracker.java:114) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.plugin.hologram.tracking.LineTracker.update(LineTracker.java:70) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.plugin.hologram.tracking.LineTrackerManager.update(LineTrackerManager.java:60) ~[HolographicDisplays.jar:?]
        at me.filoghost.holographicdisplays.plugin.tick.TickingTask.run(TickingTask.java:41) ~[HolographicDisplays.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-399] >

It says to ignore it and I try to but I would like a way to get rid of it as it does increase stress on the hosters by a little bit.

### How to reproduce

1. Install latest version of HD.
2. Start server.
3. look at console.

### Server version

1.17.1 Paper (#399)

### Holographic Displays version

3.0.0-SNAPSHOT

### Installed plugins that allow players to join with multiple Minecraft versions

N/A

**Comment by SenPr** [comment]
Any updates on this? Same issue, same paper version.

**Comment by filoghost** [comment]
This should be fixed. Try the latest dev build.
