### ISSUE TITLE
Can't use /hd or /holo

### ISSUE THREAD

**Issue by Pimdici** [filoghost/HolographicDisplays#577]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

I try to use /hd but i get a error "An internal error occured while attempting to perform this command"
I tried different version, restarting, etc
In the console it told me the plugin is disabled.

How do i fix this?

### How to reproduce

type /hd

### Server version

This server is running CraftBukkit version 3419-Spigot-862678e-c26a7b5 (MC:1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

### Holographic Displays version

 Holographic Displays v3.0.0-SNAPSHOT

### Installed plugins that allow players to join with multiple Minecraft versions

-

### Additional information

[01.02 11:40:53] [Server] [Server thread/INFO]: Pimdici issued server command: /hd
[01.02 11:40:53] [Server] [Server thread/ERROR]: null
[01.02 11:40:53] [Server] org.bukkit.command.CommandExceptionCannot execute command 'hd' in plugin HolographicDisplays v2.4.9 - plugin is disabled.
[01.02 11:40:53] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
[01.02 11:40:53] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
[01.02 11:40:53] [Server] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1945) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1784) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1765) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3419-Spigot-862678e-c26a7b5]
[01.02 11:40:53] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by filoghost** [comment]
Reading the error, you're using v2.4.9. Maybe you have two different JAR in the plugins folder?
