### ISSUE TITLE
SPam errors

### ISSUE THREAD

**Issue by ReformedHooper** [filoghost/HolographicDisplays#580]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Hello, can anyone explain for me what is this error? i dont understand this actually i updated holographicdisplays to latest version and after update i get some errors

[16:51:39 WARN]: [HolographicDisplays] Error while decoding player count from BungeeCord.
java.io.EOFException: null
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:346) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:595) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
        at me.filoghost.holographicdisplays.plugin.bridge.bungeecord.BungeeMessenger.onPluginMessageReceived(BungeeMessenger.java:61) ~[HolographicDisplays-3.0.0-SNAPSHOT (2).jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3297) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:38) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:7) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1441) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1549) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

-
-
-

### Server version

Current: git-Purpur-1547 (MC: 1.18.1)* Previous: git-Purpur-1544 (MC: 1.18.1) * You are running the latest version

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b194

**Comment by filoghost** [comment]
You are probably using a server name which doesn't exist on BungeeCord. The error handling needs to be improved, however.

**Comment by filoghost** [comment]
Should be fixed in the latest dev build, unfortunately it's not possible to tell which server name is wrong.
