### ISSUE TITLE
Hologram any placeholder problems

### ISSUE THREAD

**Issue by beautybloodtr** [filoghost/HolographicDisplays#597]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

When I restart the server, the placeholders work fine, but when we move away from the hologram and go to the hologram again, the placeholder is broken.

![image](https://user-images.githubusercontent.com/48085176/159114277-0f683472-2cc5-430e-9034-35c73b02bd8d.png)

### How to reproduce

i wrote the desc

### Server version

Current: git-Purpur-1566 (MC: 1.18.1)* * You are running the latest version

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT-b197

### Installed plugins that allow players to join with multiple Minecraft versions

no

### Additional information

[01:39:15 INFO]: BeautyBloodTR issued server command: /hd reload
[01:39:20 ERROR]: [HolographicExtension] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for HolographicExtension
java.lang.RuntimeException: Unable to clone object PacketContainer[type=ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private final int net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.a, private final java.util.List net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.b]]] (com.comphenix.protocol.events.PacketContainer)
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[ProtocolLib.jar:?]
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacketSending(PacketPlaceholderListener.java:56) ~[HolographicExtension.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:421) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2105) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2091) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:287) ~[?:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:270) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2308) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2221) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2006) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2027) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1096) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:921) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:651) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1645) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1000, banned: 0], return=Exact class net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata, params=[{Type: Exact class net.minecraft.network.PacketDataSerializer, Index: 0}], paramCount=1}
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:330) ~[ProtocolLib.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231) ~[?:?]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[ProtocolLib.jar:?]

**Comment by PZalacain** [comment]
Hello @beautybloodtr.

It's not a bug. HolographicExtension is deprecated and their functionalities are included into HolographicDisplays.
To solve your problem try to uninstall HE and configure the placeholders as the new way {papi: placeholder_name}

Give us feedback.
