### ISSUE TITLE
Not working on 1.18.2

### ISSUE THREAD

**Issue by Onionar** [filoghost/HolographicDisplays#604]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

So I use the latest development build released on Mar 12. It does not work. First off in the console in says:
[HolographicDisplays] Enabling HolographicDisplays v2.4.9
[21:28:18 INFO]:
[21:28:18 INFO]:  
[21:28:18 INFO]: ****************************************************************************
[21:28:18 INFO]:     Holographic Displays does not support this server version.
[21:28:18 INFO]:     Supported Spigot versions: from 1.8.3 to 1.16.4.
[21:28:18 INFO]:  
[21:28:18 INFO]:     This plugin has been disabled.
[21:28:18 INFO]: ****************************************************************************

**Then under that there is error with update:**

[HolographicDisplays] Unable to check for updates: unhandled exception.
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[purpur-1.18.2.jar:git-Purpur-1611]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[purpur-1.18.2.jar:git-Purpur-1611]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[purpur-1.18.2.jar:git-Purpur-1611]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[purpur-1.18.2.jar:git-Purpur-1611]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[purpur-1.18.2.jar:git-Purpur-1611]
at com.gmail.filoghost.holographicdisplays.updater.UpdateChecker.lambda$run$1(UpdateChecker.java:63) ~[HolographicDisplays.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1611]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1611]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1611]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**And when I try to execute "hd" command, it does not work and error occurs:**

[21:32:49 WARN]: Unexpected exception while parsing console command "hd"
org.bukkit.command.CommandException: Cannot execute command 'hd' in plugin HolographicDisplays v2.4.9 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1611]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1611]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1611]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1611]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1611]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1611]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1611]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

IDK

### Server version

Current: git-Purpur-1611 (MC: 1.18.2)* (Purpur is fork of PaperSpigot, which is fork of Spigot)

### Holographic Displays version

Does not work

### Installed plugins that allow players to join with multiple Minecraft versions

none

**Comment by Jeppa** [comment]
You should realy update to 'latest'...
v2.4.9 is from 2021!
You need to update to V3.0.0 Snapshot

**Comment by Onionar** [comment]
Thats the problem, I use the latest V3.0.0 Snapshot but it still says that thing in console

**Comment by Kopo942** [comment]
The first row in your logs is literally `[HolographicDisplays] Enabling HolographicDisplays v2.4.9`, so you're definitely not using 3.0.0. Double check your plugins folder.

**Comment by filoghost** [comment]
As they said, you probably have multiple versions in the plugins folder, or loaded externally somehow. What is happening is not the plugin's fault.
