### ISSUE TITLE
Unable to check for updates error

### ISSUE THREAD

**Issue by rishabhk571** [filoghost/HolographicDisplays#608]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

Got the below error in the console while enabling Holographic Displays and it is not enabled

```
[09:07:05 WARN]: [HolographicDisplays] Unable to check for updates: unhandled exception.
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.18.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.18.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[paper-1.18.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[paper-1.18.2.jar:git-Paper-312]
        at com.gmail.filoghost.holographicdisplays.updater.UpdateChecker.lambda$run$1(UpdateChecker.java:63) ~[HolographicDisplays.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-312]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Plugins in my server -
```
[09:07:55 INFO]: Plugins (25): AdvancedEnchantments, AdvancedLogin*, DeluxeHub, Essentials, Factions, floodgate, Geyser-Spigot, Hibernate, HolographicDisplays, LiteBans, LuckPerms, Matrix, NexEngine, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, RedstoneClockDetector*, ServersNPC, ShopGUIPlus, TCPShield, UltimateAntiBot, Vault, ViaBackwards, ViaRewind, ViaVersion
```

I also got following error from Placeholder API:
```
[09:08:54 WARN]: [PlaceholderAPI] Failed to download expansion information
java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at java.net.Socket.connect(Socket.java:583) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:373) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at java.net.URL.openStream(URL.java:1161) ~[?:?]
        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.io.ByteSource.read(ByteSource.java:296) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:486) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.io.Resources.toString(Resources.java:111) ~[guava-31.0.1-jre.jar:?]
        at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$fetch$4(CloudExpansionManager.java:180) ~[PlaceholderAPI-2.11.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Holographic Displays version

HolographicDisplays version 2.4.9

**Comment by filoghost** [comment]
Please update to the beta v3.
