### ISSUE TITLE
HolographicDisplays is facing some problem while decoding the player count from my Bungeecord Network.

### ISSUE THREAD

**Issue by MagneticHydra** [filoghost/HolographicDisplays#616]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

I have Bungeecord enabled in spigot.yml
And the proxy is online.

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Additional information

[14:43:48 WARN]: [HolographicDisplays] Error while decoding player count from BungeeCord.
java.io.EOFException: null
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:345) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
        at me.filoghost.holographicdisplays.plugin.bridge.bungeecord.BungeeMessenger.onPluginMessageReceived(BungeeMessenger.java:61) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) ~[vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2367) ~[vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:24) ~[vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:5) ~[vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:6) ~[vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [vanilla.jar:git-NachoSpigot-"0f4e14e"]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[14:43:48 INFO]: M_HydraPlaysMC lost connection: Disconnected

**Comment by filoghost** [comment]
I think it happens when the server name is not found on BungeeCord. Can you confirm?
