### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by adviis** [filoghost/HolographicDisplays#632]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Hello, when I try to use API, I get an error. Below is the simplest code showing error. 
Have a nice day!

### How to reproduce

```
package com.company;

import me.filoghost.holographicdisplays.api.HolographicDisplaysAPI;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;

public class Main extends JavaPlugin {
    // plugin.yml
    //name: BUG-REPORT
    //author: Me
    //version: 0.0.1
    //main: com.company.Main
    //softdepend:
    //  - HolographicDisplays
    public HolographicDisplaysAPI holoAPI;
    public void onEnable() {
        Plugin plugin = this;
        holoAPI = HolographicDisplaysAPI.get(plugin);
        System.out.println("Test plugin on");
    }
}

```

### Server version

Paper 1.16.5

### Holographic Displays version

3.0.0-SNAPSHOT-b225

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

### Additional information

HoloAPI version: 3.0.0-20220619.091120-48

```
    //[05:44:33 INFO]: [BUG-REPORT] Enabling BUG-REPORT v0.0.1*
    //[05:44:33 ERROR]: Error occurred while enabling BUG-REPORT v0.0.1 (Is it up to date?)
    //java.lang.IllegalStateException: Holographic Displays did not load properly (no API implementation was set)
    //        at me.filoghost.holographicdisplays.api.internal.HolographicDisplaysAPIProvider.getImplementation(HolographicDisplaysAPIProvider.java:30) ~[?:?]
    //        at me.filoghost.holographicdisplays.api.HolographicDisplaysAPI.get(HolographicDisplaysAPI.java:60) ~[?:?]
    //        at com.company.Main.onEnable(Main.java:18) ~[?:?]
    //        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
    //        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
    //        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
    //        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
    //        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
    //        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
    //        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
    //        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
    //        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
    //        at java.lang.Thread.run(Thread.java:833) [?:?]
    //[05:44:33 INFO]: [BUG-REPORT] Disabling BUG-REPORT v0.0.1
```

**Comment by filoghost** [comment]
Can you please post the full log?
