### ISSUE TITLE
Plugin wont load due to duplicate hologram name after updating to 1.19

### ISSUE THREAD

**Issue by DaliborTrampota** [filoghost/HolographicDisplays#644]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/holographic-displays).
- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).

### Description

13:07:01[INFO] [HolographicDisplays] Enabling HolographicDisplays v3.0.0-SNAPSHOT-b226
13:07:01[INFO] [HolographicDisplays] Fatal unexpected error while enabling HolographicDisplays v3.0.0-SNAPSHOT-b226:
java.lang.IllegalStateException: hologram named "shop" already exists
at HolographicDisplays-3.0.0-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.internal.hologram.InternalHologramManager.createHologram(InternalHologramManager.java:37)
at HolographicDisplays-3.0.0-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.HolographicDisplays.load(HolographicDisplays.java:141)
at HolographicDisplays-3.0.0-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.HolographicDisplays.onCheckedEnable(HolographicDisplays.java:93)
at HolographicDisplays-3.0.0-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.lib.fcommons.FCommonsPlugin.onEnable(FCommonsPlugin.java:22)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1124)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
at java.base/java.lang.Thread.run(Unknown Source)
The plugin has been disabled.

### Holographic Displays version

HolographicDisplays v3.0.0-SNAPSHOT-b226

**Comment by filoghost** [comment]
Did you manually edit the database? It shouldn't be possible to end up with this situation.
