### ISSUE TITLE
Some Warning

### ISSUE THREAD

**Issue by rishabhk571** [filoghost/HolographicDisplays#651]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

```[15:00:07 WARN]: [HoloExtension] Plugin HoloExtension v0.1.0.1 Alpha generated an exception while executing task 1183
java.lang.NumberFormatException: For input string: "%statistic_seconds_played%"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.parseStringToDouble(PapiModule.java:92) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.tick(PapiModule.java:56) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.LeaderBoardManager.lambda$tick$1(LeaderBoardManager.java:198) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.18.2.jar:git-Paper-347]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-347]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-347]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:00:07 INFO]: Hooked EconomyShopGUI as item price. (Config: EconomyShopGUI, Hook name: EconomyShopGUI)
[15:00:26 WARN]: [HoloExtension] Plugin HoloExtension v0.1.0.1 Alpha generated an exception while executing task 2280
java.lang.NumberFormatException: For input string: "%statistic_seconds_played%"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.parseStringToDouble(PapiModule.java:92) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.tick(PapiModule.java:56) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.LeaderBoardManager.lambda$tick$1(LeaderBoardManager.java:198) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.18.2.jar:git-Paper-347]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-347]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-347]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:00:46 WARN]: [HoloExtension] Plugin HoloExtension v0.1.0.1 Alpha generated an exception while executing task 2683
java.lang.NumberFormatException: For input string: "%statistic_seconds_played%"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.parseStringToDouble(PapiModule.java:92) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.tick(PapiModule.java:56) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.LeaderBoardManager.lambda$tick$1(LeaderBoardManager.java:198) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.18.2.jar:git-Paper-347]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-347]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-347]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:01:06 WARN]: [HoloExtension] Plugin HoloExtension v0.1.0.1 Alpha generated an exception while executing task 3085
java.lang.NumberFormatException: For input string: "%statistic_seconds_played%"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.parseStringToDouble(PapiModule.java:92) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.modules.PapiModule.tick(PapiModule.java:56) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at eu.virtusdevelops.holoextension.leaderboards.LeaderBoardManager.lambda$tick$1(LeaderBoardManager.java:198) ~[HoloExtension-0.1.0.1 Alpha-all.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.18.2.jar:git-Paper-347]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-347]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-347]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

### How to reproduce

idk

### Server version

```This server is running Paper version git-Paper-347 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 79e07f3)```

### Holographic Displays version

[15:02:38 INFO]: HoloExtension version 0.1.0.1 Alpha [15:02:38 INFO]: Author: NeutralPlasma

### Installed plugins that allow players to join with multiple Minecraft versions

Via Version, Via Backwards, Via Rewind

### Additional information

```AureliumSkills, BuildersWand, Citizens, CMILib, CombatPlus, DeluxeHub, DiscordSRV, EconomyShopGUI, EpicHoppers, Essentials, ExcellentCrates, floodgate, Geyser-Spigot, HoloExtension, HolographicDisplays, HoloRemove*, IridiumSkyblock, Jobs, LuckPerms, Maintenance, NexEngine, PlaceholderAPI, PlayerWarps, ProtocolLib, SCore, SecurityLog, Sellwand, SilkSpawners, SimpleScore, SkinsRestorer, SuperbVote*, UltimateAntiBot*, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, Webvotelogger, WorldEdit, WorldGuard``` My Plugins

**Comment by filoghost** [comment]
Cause by HoloExtension, not Holographic Displays.
