### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 2006lev-Web** [filoghost/HolographicDisplays#653]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

`[16:16:31 WARN]: [HolographicDisplays] Unable to get a stacktrace element, please inform the developer. You will only see this error once to avoid spam.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceElement(int)
        at java.lang.Class.getDeclaredMethod(Class.java:2475) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.util.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:44) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.getId(EntityNMSArmorStand.java:139) [HolographicDisplays.jar:?]
        at net.minecraft.server.v1_12_R1.PacketPlayOutEntityTeleport.<init>(SourceFile:22) [server.jar:git-Spigot-eb3d921-2b93d83]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:202) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:106) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:75) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:300) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:247) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.subs.ReloadCommand.execute(ReloadCommand.java:81) [HolographicDisplays.jar:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:95) [HolographicDisplays.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [server.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) [server.jar:git-Spigot-eb3d921-2b93d83]
        at dk.lockfuglsang.wolfencraft.config.Scoreboard.refreshView(Scoreboard.java:133) [HolographicScoreboard.jar:?]
        at dk.lockfuglsang.wolfencraft.HolographicScoreboard$2.run(HolographicScoreboard.java:105) [HolographicScoreboard.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [server.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-eb3d921-2b93d83]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

### How to reproduce

installed ViaVersion

### Server version

This server is running CraftBukkit version git-Spigot-eb3d921-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Holographic Displays version

HolographicDisplays version 2.2.6

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

**Comment by filoghost** [comment]
Please update, you're using a version from more than 5 years ago.

**Comment by 2006lev-Web** [comment]
I updated the plugins and the error started coming out I can't understand
![Screenshot_9](https://user-images.githubusercontent.com/64630503/199429283-5645e705-791b-4e62-9e71-a7c0fdde5055.png)

**Comment by filoghost** [comment]
You're still using the old version I think. The format of that file has changed. Also please do not manually edit the database.

**Comment by filoghost** [comment]
Provide a copy of that file so I can try it.

**Comment by 2006lev-Web** [comment]
[database.txt](https://github.com/filoghost/HolographicDisplays/files/9943290/database.txt)
here only the txt format is allowed

**Comment by filoghost** [comment]
I'm not even sure how the YAML file became like that. The old version doesn't load it, even online parsers report it as wrong. You need to add single quotes (`'`) at the start and at the end of each line.

Like this:
```yaml
lines:
- 'Line 1'
- 'Line 2'
```
