### ISSUE TITLE
Console spam with error

### ISSUE THREAD

**Issue by Benntehboss** [filoghost/HolographicDisplays#683]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Spams my log, with errors as soon as server starts up, if i make new holos or uses a plugin that use holos

[10:51:26] [Server thread/ERROR]: [HolographicDisplays] Error while ticking holograms
java.lang.StackOverflowError: null
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]
	at me.filoghost.holographicdisplays.nms.v1_8_R3.PacketByteBuffer.writeVarInt(PacketByteBuffer.java:30) ~[?:?]
	at net.minecraft.server.v1_8_R3.PacketDataSerializer.b(PacketDataSerializer.java:146) ~[server.jar:git-ReliableSpigot-"975138d"]

### How to reproduce

load server with reliablespigot and holograms.
use any plugin that uses holograms
reload hologram to stop spam briefly, but holograms dosent work

### Server version

ReliableSpigot Version 2.4.4 (MC: 1.8.8)

### Holographic Displays version

3.0.2snapshot-b246

### Installed plugins that allow players to join with multiple Minecraft versions

viaversion 3.2.1 protocollib 4.8.0

### Additional information

https://pastebin.com/aPv94vU8

**Comment by Benntehboss** [comment]
come in 3.0.0 and above.

**Comment by filoghost** [comment]
Can you please try with the latest dev build?
