### ISSUE TITLE
An Internal Error Occured While Attempting To Perform This Command

### ISSUE THREAD

**Issue by TOMKEZ** [filoghost/HolographicDisplays#687]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [x] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Hello, when I try to execute any command, I see this error in the console
org.bukkit.command.CommandException: Cannot execute command 'hd' in plugin HolographicDisplays v3.0.2-SNAPSHOT-b246 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[bukkit-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:826) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1921) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1883) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1113) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1092) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1085) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:115) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1068) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:987) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[craftbukkit-1.19.3-R0.1-SNAPSHOT.jar:3611-Bukkit-19e6be0]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Have HolographicDisplays for 1.19.3

### Server version

CraftBukkit 1.19.3

### Holographic Displays version

HolographicDisplays-3.0.2-SNAPSHOT (I try on the 3.0.1 version too)

**Comment by filoghost** [comment]
The plugin is not enabled, maybe because it's not loading properly. Check startup error messages, or if any other plugin is disabling Holographic Displays.
