### ISSUE TITLE
not compatable with Paper 1.19.4

### ISSUE THREAD

**Issue by Tsoccerguy3** [filoghost/HolographicDisplays#690]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

 Needs support for 1.19.4

### How to reproduce

Early stage testing , missing support for new 1.19.4 API

### Server version

Paper 1.19.4

### Holographic Displays version

HolographicDisplays-3.0.2-SNAPSHOT.jar

**Comment by Budderman18** [comment]
I've fixed this myself. You can find it my going under "forks" and finding the one with my username.

**Comment by Tsoccerguy3** [comment]
Thank you Budderman , I pulled your fixes . Your Pom.xml is missing references to 1.19.3 and 1.19.4 and fails to compile on the checks until you add them .

G:\Dev\holo1194>mvn install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for me.filoghost.holographicdisplays:holographicdisplays-nms-v1_19_r3:jar is missing. @ line 117, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project me.filoghost.holographicdisplays:holographicdisplays-core:3.0.2-SNAPSHOT (G:\Dev\holo1194\core\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for me.filoghost.holographicdisplays:holographicdisplays-nms-v1_19_r3:jar is missing. @ line 117, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException



 I tested your build and its working . 

For other people that land here , here is Budderman's release https://github.com/Budderman18/HolographicDisplays/releases/tag/release

**Comment by Tsoccerguy3** [comment]
Floghost's dev build is not finished yet , don't use the build , wait for 1.19.4 support . Clean up in progress

[15:09:12 INFO]: [HolographicDisplays] Fatal error while enabling HolographicDisplays v3.0.2-SNAPSHOT-b248:

Holographic Displays only supports Spigot from 1.8 to 1.19.3.
The plugin has been disabled.

**Comment by Feldmarschall** [comment]
```
[18:25:35 ERROR]: Could not pass event PlayerQuitEvent to HolographicDisplays v3.0.2-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "channel" is null
        at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.modifyPipeline(VersionNMSManager.java:104) ~[holographicdisplays-plugin-3.0.2-alpha.jar:?]
        at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.uninjectPacketListener(VersionNMSManager.java:87) ~[holographicdisplays-plugin-3.0.2-alpha.jar:?]
        at me.filoghost.holographicdisplays.core.listener.PlayerListener.onPlayerQuit(PlayerListener.java:41) ~[holographicdisplays-plugin-3.0.2-alpha.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor66.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-466]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-466]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-466]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:585) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2111) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:523) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:473) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:404) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by MelonHell** [comment]
> with ur build @Budderman18
> 
> ```
> [18:25:35 ERROR]: Could not pass event PlayerQuitEvent to HolographicDisplays v3.0.2-SNAPSHOT
> java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "channel" is null
>         at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.modifyPipeline(VersionNMSManager.java:104) ~[holographicdisplays-plugin-3.0.2-alpha.jar:?]
>         at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.uninjectPacketListener(VersionNMSManager.java:87) ~[holographicdisplays-plugin-3.0.2-alpha.jar:?]
>         at me.filoghost.holographicdisplays.core.listener.PlayerListener.onPlayerQuit(PlayerListener.java:41) ~[holographicdisplays-plugin-3.0.2-alpha.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor66.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-466]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-466]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-466]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
>         at net.minecraft.server.players.PlayerList.remove(PlayerList.java:585) ~[paper-1.19.4.jar:git-Paper-466]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2111) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:523) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:473) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:404) ~[?:?]
>         at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
>         at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[paper-1.19.4.jar:git-Paper-466]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-466]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-466]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-466]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-466]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

+1

**Comment by Leahcimkrob** [comment]
@Budderman18 
We get this message with your Version:
[20:47:45] [Server thread/INFO]: [HolographicDisplays] Encountered 1 error(s) on load:
 
1) Could not get the NMS entity ID generator. There is a small chance of entity ID conflicts, causing client-side issues on single entities.
------------[ Exception details ]------------
java.lang.ReflectiveOperationException: java.lang.ClassCastException: Cannot cast org.apache.logging.slf4j.Log4jLogger to java.util.concurrent.atomic.AtomicInteger
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.lib.fcommons.reflection.ValidReflectField.get(ValidReflectField.java:53)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.lib.fcommons.reflection.ValidReflectField.getStatic(ValidReflectField.java:41)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.getEntityIDGenerator(VersionNMSManager.java:47)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.<init>(VersionNMSManager.java:39)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.core.NMSVersion.lambda$static$16(NMSVersion.java:43)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.core.NMSVersion.createNMSManager(NMSVersion.java:55)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.core.HolographicDisplaysCore.enable(HolographicDisplaysCore.java:41)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.HolographicDisplays.onCheckedEnable(HolographicDisplays.java:80)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.lib.fcommons.FCommonsPlugin.onEnable(FCommonsPlugin.java:22)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: Cannot cast org.apache.logging.slf4j.Log4jLogger to java.util.concurrent.atomic.AtomicInteger
	at java.base/java.lang.Class.cast(Class.java:3921)
	at holographicdisplays-plugin-3.0.2-SNAPSHOT.jar//me.filoghost.holographicdisplays.plugin.lib.fcommons.reflection.ValidReflectField.get(ValidReflectField.java:49)
	... 20 more
---------------------------------------------

**Comment by KC-1508** [comment]
Resolved https://github.com/filoghost/HolographicDisplays/commit/2b5afc82af6d78d7f6fcc05a0ce67274483b1422
