### ISSUE TITLE
when the player leave the server it show this bugs

### ISSUE THREAD

**Issue by YouKlike** [filoghost/HolographicDisplays#695]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

[20:45:52 ERROR]: Could not pass event PlayerJoinEvent to HolographicDisplays v3.0.2-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "channel" is null
        at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.modifyPipeline(VersionNMSManager.java:104) ~[holographicdisplays-plugin-3.0.2-SNAPSHOT.jar:?]
        at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.injectPacketListener(VersionNMSManager.java:76) ~[holographicdisplays-plugin-3.0.2-SNAPSHOT.jar:?]
        at me.filoghost.holographicdisplays.core.listener.PlayerListener.onPlayerJoin(PlayerListener.java:33) ~[holographicdisplays-plugin-3.0.2-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor297.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1964]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:330) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1605) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1964]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

1. when the player leave the server it show this bugs

### Server version

1.19.4

### Holographic Displays version

HolographicDisplays-3.0.2

### Installed plugins that allow players to join with multiple Minecraft versions

no

### Additional information

when the player leave the server it show this bugs

**Comment by filoghost** [comment]
Was the player instantly kicked the moment he joined? Because I see `onPlayerJoin` which means that the error is generated on a join event, not a quit event.

**Comment by YouKlike** [comment]
yes

**Comment by filoghost** [comment]
Fixed this error in particular in the latest version, however it's closely related to #712
