### ISSUE TITLE
Cannot invoke "me.filoghost.holographicdisplays.api.hologram.Hologram.getLines()" because "hologram" is null

### ISSUE THREAD

**Issue by vertanzil** [filoghost/HolographicDisplays#710]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Noticed that when I look in our servers log file it is currently being spammed with the error below.

### How to reproduce

1. Install the plugin
2. Create holograms
3. Wait

### Server version

1.20.1

### Holographic Displays version

3.0.3

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards. ViaRewind, Viarewind-Legacy, ViaVersionStatus

### Additional information

[12:23:17] [Server thread/WARN]: [FLB] Task #41 for FLB v1 generated an exception
java.lang.NullPointerException: Cannot invoke "me.filoghost.holographicdisplays.api.hologram.Hologram.getLines()" because "hologram" is null
	at iso.jimmy.Updater.updateHolo(Updater.java:32) ~[FactionsLeaderboard.jar:?]
	at iso.jimmy.UpdaterTask.run(UpdaterTask.java:20) ~[FactionsLeaderboard.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by filoghost** [comment]
That's because your variable named "hologram" is null. It says it right in the exception message.
