### ISSUE TITLE
NMS issue with Paper

### ISSUE THREAD

**Issue by Thekillinghoboz** [filoghost/HolographicDisplays#83]
When executing the command /holo create <name> icon:potato (or any item/icon) an error is thrown. I'm guessing the NMS isn't supported with paper version git-Paper-1430.

`[16:49:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'holo' in plugin HolographicDisplays v2.2.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1430]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1430]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1430]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1430]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_12_R1.ItemStack.F(ItemStack.java:116) ~[patched_1.12.2.jar:git-Paper-1430]
        at net.minecraft.server.v1_12_R1.ItemStack.setCount(ItemStack.java:866) ~[patched_1.12.2.jar:git-Paper-1430]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.EntityNMSItem.setItemStackNMS(EntityNMSItem.java:174) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_12_R1.NmsManagerImpl.spawnNMSItem(NmsManagerImpl.java:84) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.spawn(CraftItemLine.java:86) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:300) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:247) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.subs.CreateCommand.execute(CreateCommand.java:71) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.commands.main.HologramsCommandHandler.onCommand(HologramsCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1430]
        ... 15 more
`

**Comment by filoghost** [comment]
I've found the source of the problem: this error occurs when the material is invalid or not an item (= cannot be hold in the inventory or exist as item drop). "potato" represents the block (cannot be hold in the inventory), "potato_item" represents the item (can be hold in the inventory).

**Comment by filoghost** [comment]
https://github.com/filoghost/HolographicDisplays/commit/49d6930389d5aa8eb7040926a92f9d6ebf3b9e36
