### ISSUE TITLE
appendline error

### ISSUE THREAD

**Issue by lzy233AB** [filoghost/HolographicDisplays#92]
Hologram hologram = HologramsAPI.createHologram(this, loc);
hologram.appendTextLine("233333");

then ....
holo.clearLines();
holo.appendTextLine("balalaaaa");

error
`    Caused by: java.lang.IllegalArgumentException: Async entity add
   at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:13) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_13_R1.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:121) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.nms.v1_13_R1.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:114) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:75) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshSingleLines(CraftHologram.java:270) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:120) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:26) ~[?:?]`

**Comment by filoghost** [comment]
You're executing the code asynchronously, you should not.
